### ISSUE TITLE
Email Login Problem

### ISSUE THREAD

**Issue by rahidulislam** [elementary/mail#815] opened 2023-02-01 07:34 UTC
### What Happened?

When I am trying to login my gmail with elementary os 7 Horus default mail. its failed to login

### Steps to Reproduce

1. go to settings
2. online account
3. click (+) sign
4. IMAP
5. email and password
6. login

### Expected Behavior

i want to login gmail account

### OS Version

7.x (Early Access)

### Software Version

Latest release (I have run all updates)

**Comment by tintou** [comment] 2023-02-01 07:48
Duplicate of #789

TL;DR: GMail is actively discouraging the use of 3rd party apps, you need to generate an app password for it to work.

**Closed by tintou** 2023-02-01 07:48 UTC

**Comment by rahidulislam** [comment] 2023-02-11 08:20
i tried to login with app password. but same issue
