### ISSUE TITLE
Window size bigger every time the application is opened

### ISSUE THREAD

**Issue by inad9300** [elementary/mail#411] opened 2019-08-02 15:00 UTC
Every time I open Mail, it is bigger than before closing it, in both dimensions. It doesn't remember the closing size properly.

**Comment by danrabbit** [comment] 2019-08-02 15:04
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2019-08-02 15:04 UTC

**Comment by happyrobotstudio** [comment] 2019-08-02 18:24
Cool to hear danrabbit

This issue was a non-starter for me whether using or contributing =) Looking forward to new Mail
