### ISSUE TITLE
I can't delete an account

### ISSUE THREAD

**Issue by yormi-altamiranda** [elementary/mail#416] opened 2019-09-06 14:25 UTC
I cannot delete the account a gmail account, the option (-) is disabled.
in trying to add another account and it tells me an error in the username or password.

**Comment by danrabbit** [comment] 2020-12-21 22:20
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2020-12-21 22:20 UTC
