### ISSUE TITLE
Mail Accounts settings dialog exceeds screen length and can't see settings below the sreen

### ISSUE THREAD

**Issue by uncertainquark** [elementary/mail#24] opened 2017-05-19 15:22 UTC
Here is what I am talking about:
![screenshot from 2017-05-19 20 22 18](https://cloud.githubusercontent.com/assets/22585732/26254657/d5522938-3ca6-11e7-96bc-83b083c0e62d.png)

The Settings dialog, even if extended to full screen length doesn't show all the settings. Dragging the window upwards using the mouse doesn't work either (in this case, its the email signature and stuff below it).

This issue happens when you have added an account through Switchboard Settings > Online Accounts.
The issue doesn't happen if the account is added via the Mail app itself

**Comment by danrabbit** [comment] 2017-05-19 15:38
Closing as a duplicate of #11

**Closed by danrabbit** 2017-05-19 15:38 UTC
