### ISSUE TITLE
Archive shortcut key not working

### ISSUE THREAD

**Issue by therocco** [elementary/mail#301] opened 2018-10-24 21:07 UTC
Updated my system this morning and since that time the `A` shortcut key for archiving mail is no longer working. Tested on multiple machines with the same email account and the archive shortcut stopped working on all of them.

**Comment by danrabbit** [comment] 2018-10-24 21:20
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2018-10-24 21:20 UTC
