### ISSUE TITLE
Deletion and notifications

### ISSUE THREAD

**Issue by Tenanka** [elementary/mail#643] opened 2021-08-13 19:03 UTC
E-Mail client 

1.	 Add account (hotmail) problematic server settings are not correct
IMAP server name http://outlook.office365.com

IMAP port: 993

IMAP TLS encryption method

POP server name http://outlook.office365.com

POP port: 995

POP TLS encryption method

SMTP server name: http://smtp-mail.outlook.com

SMTP port: 587

SMTP encryption method STARTTLS

2.	Deleted emails do not go to the trash
3.	French translation is not complete.
4.	Deleting a mail should normally display the next mail but it is not the case, and the "cancel" notification would appear after deletions and annoying 

Sorry for my english 
2.
3.

**Comment by marbetschar** [comment] 2021-08-16 10:26
Please open an issue for one thing at a time. This makes the issue both more concise and more actionable - otherwise things get messy quite quickly :)

As for the stuff mentioned here:

**1. Deleted emails do not go to the trash:**
    Duplicate of https://github.com/elementary/mail/issues/647

**2. French translation is not complete:**
    We are always happy to add translations! Please follow the guideance provided here to add whatever you are missing: https://elementary.io/get-involved

**3. Deleting a mail should display the next mail:**
    Duplicate of https://github.com/elementary/mail/issues/641

Closing this issue because there are other, more specific issues for the things mentioned here.

**Closed by marbetschar** 2021-08-16 10:26 UTC
