### ISSUE TITLE
Geary doesn't show all mailing addresses (and names) in the "To" and "cc/bcc" sections:

### ISSUE THREAD

**Issue by uncertainquark** [elementary/mail#198] opened 2018-03-24 11:06 UTC
Replicate by sending a mail to multiple people (>5).

![screenshot from 2018-03-23 12 41 35](https://user-images.githubusercontent.com/22585732/37863264-7d4172de-2f81-11e8-9eb0-7fe62f4a5df4.png)

The mail app just cuts the other email addresses and only shows as much as it can in one line instead of showing them all in multiple lines.

This is quite a major issue that renders the entire app unusable in large organizations.

**Comment by danrabbit** [comment] 2019-06-11 00:24
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2019-06-11 00:24 UTC
Labels: Status: Confirmed
