### ISSUE TITLE
High memory usage while running in background

### ISSUE THREAD

**Issue by Tomires** [elementary/mail#187] opened 2018-01-30 22:56 UTC
Memory usage routinely reaches 500-600 MB while running in background. Debug mode doesn't tell me anything (left it running for 20 minutes and received no errors/messages whatsoever). I use 4 e-mail accounts (1 gmail + 3 private server accounts). Disabling notifications in settings (not surprisingly) mitigates this issue.

Here is a screen from the task manager:

![screenshot from 2018-01-30 21 17 56](https://user-images.githubusercontent.com/7209990/35595803-2f05f352-0618-11e8-91d3-e72aa11cfa4d.jpeg)

Can provide more info if needed.

**Comment by roymckenzie** [comment] 2018-03-09 23:16
Pantheon Mail will continue to increase it's memory footprint on my system as well.

Every time I start elementary OS I open terminal and do the following so it doesn't eat up all my resources:

```bash
$ pgrep mail
1931
$ kill 1931
```

**Comment by Tomires** [comment] 2018-03-10 00:00
Why not just disable the notifications in Mail's settings? It (presumably) accomplishes the same thing as killing the daemon and you don't have to do it manually.

**Comment by roymckenzie** [comment] 2018-03-10 00:02
@Tomires is the reason why it's taking up so much system memory because of notifications?

**Comment by Tomires** [comment] 2018-03-10 00:07
Seems like so. I can't think of anything else that the daemon could do besides fetching new mail. The most likely scenario is a memory leak in the fetching procedure.

**Comment by roymckenzie** [comment] 2018-03-10 00:09
@Tomires thanks!

**Comment by danrabbit** [comment] 2018-10-17 15:57
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2018-10-17 15:57 UTC
