### ISSUE TITLE
Core dump when searching for a specific name

### ISSUE THREAD

**Issue by icex** [elementary/mail#227] opened 2018-08-03 23:05 UTC
Hello,

I get a core dump when I search for "Alex" only in my gmail account. I haven't had any issues with other phrases or names. This one crashes every single time.

~$ pantheon-mail

(pantheon-mail:25170): Gtk-WARNING **: 01:45:22.882: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
Segmentation fault (core dumped)

I don't know where and if the core dump is written so I can attach it here.

I'm running:
Description:	elementary OS 5.0 Juno
Release:	5.0
Linux bogdan-Lenovo-720S-15ikb 4.17.12-041712-generic #201808030231 SMP Fri Aug 3 06:34:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

dpkg -s pantheon-mail | grep Version
Version: 1.0.7+r2457+pkg16~ubuntu5.0.1

dpkg -s libgdk-pixbuf2.0-0 | grep Version
Version: 2.36.11-2

**Comment by danrabbit** [comment] 2018-10-17 15:55
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2018-10-17 15:55 UTC
