### ISSUE TITLE
Sometimes external images do not load (Medium.com)

### ISSUE THREAD

**Issue by wout** [elementary/mail#304] opened 2018-10-26 20:33 UTC
On all mails form Medium, images show as grey area's:

![image](https://user-images.githubusercontent.com/107324/47591192-f1bb1600-d96e-11e8-9b2b-99c3bfdee410.png)

It happens with other mails as well.

**Comment by danrabbit** [comment] 2019-06-11 00:04
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2019-06-11 00:04 UTC
