### ISSUE TITLE
Make Mail a Flatpak-first application

### ISSUE THREAD

**Issue by tintou** [elementary/mail#426] opened 2019-10-07 06:29 UTC
We have a chance to design an application with Flatpak in mind from day one, we should probably ship it as a Flatpak by default

**Comment by saidbakr** [comment] 2019-12-07 23:12
I disagree. I regard that Flatpaks another fresh faulty project exactly the same like Unity. There is no any sense with downloading 1.3 GB for a package that may worth just 40 MB from the PPA. Indeed, it is a silly joke!

**Comment by danrabbit** [comment] 2020-10-20 21:53
Gonna close this as a duplicate of #124

**Closed by danrabbit** 2020-10-20 21:53 UTC
Labels: Priority: Wishlist
