### ISSUE TITLE
Some emails do not unfold

### ISSUE THREAD

**Issue by Bassi380** [elementary/mail#668] opened 2021-08-30 13:02 UTC
![Bildschirmfoto von 2021-08-30 14-44-40](https://user-images.githubusercontent.com/83209462/131342968-23f4df87-491a-4cab-94a6-4168c91f5c9c.png)

**Comment by marbetschar** [comment] 2021-08-30 13:06
@Bassi380 thanks for the bug report! This issue has already been addressed in https://github.com/elementary/mail/pull/655 and should be fixed with the next release of Mail.

Therefore I'm closing this issue as duplicate of https://github.com/elementary/mail/issues/582 - but feel free to re-open if the issue is not fixed after the update!

**Closed by marbetschar** 2021-08-30 13:06 UTC
