### ISSUE TITLE
Message body creeps down

### ISSUE THREAD

**Issue by Djaler** [elementary/mail#190] opened 2018-02-10 13:19 UTC
If I open one of my messages and resize right panel, message body just start to creeps down. You can see it in action by the [link](https://youtu.be/rxZXDVLL9Zk). I can forward this message to you, if it can help you to solve the problem.

**Comment by danrabbit** [comment] 2020-12-21 22:13
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2020-12-21 22:13 UTC
