### ISSUE TITLE
Swip Support

### ISSUE THREAD

**Issue by OssNass** [elementary/mail#642] opened 2021-08-13 06:17 UTC
## Problem
As mouse gestures are becoming integral for Elementary OS user experience, supporting deleting or archiving emails using mouse gestures in mail is a nice feature to have

## Proposal
Add support for mouse gestures to delete/archive emails using 2 fingers mouse gestures by swiping left for archive, and right for delete

**Comment by danrabbit** [comment] 2021-09-09 21:13
Looks like this is a duplicate of #551

**Closed by danrabbit** 2021-09-09 21:13 UTC
Labels: Enhancement
