### ISSUE TITLE
Mail not sending messages

### ISSUE THREAD

**Issue by Tchutcha877** [elementary/mail#344] opened 2019-01-12 19:06 UTC
I can't send an e-mail from my mail client, when I click send it just goes to my "sending" box and after a while it displays an error saying that There was a failure, if the problem persists manually delete the file. While I do this the message entirely deletes, even the received ones from my inbox, this is a problem. I tried it with several tests sending mails to my other account and I was never successful. 
How can I resolve this problem? I need to answer a lot of e-mails for work and this application helps me with that, but not being able to send e-mails is getting really impossible to use it :/

**Comment by danrabbit** [comment] 2019-02-13 06:48
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2019-02-13 06:48 UTC
