### ISSUE TITLE
resizing window resets scroll in mail pane

### ISSUE THREAD

**Issue by Nine-H** [elementary/mail#39] opened 2017-06-13 03:54 UTC
which doesn't feel very nice.

**Comment by danrabbit** [comment] 2018-10-22 22:44
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2018-10-22 22:44 UTC
Labels: Priority: Low, Status: Confirmed
