### ISSUE TITLE
Window and columns settings

### ISSUE THREAD

**Issue by grmain** [elementary/mail#430] opened 2019-10-26 13:27 UTC
Hi,
Pantheon Mail keeps ignoring everything I do with and within the main window: 
- size and position of the window: at each startup of my computer, each launch of Pantheon Mail maximises the window and put it on my secondary screen which is turned off 99% of the time. Really annoying
- size of the columns and lists of my account's folders: everything comes back set by default. I want to see all my folders in the left column, I want my messages' list wider, etc. Mail let me do that, that's cool, but it forgets everything at each startup. Really annoying too.

Actually, other things ignore my settings in elementary OS: default sound card, deactivation of my secondary screen.
eOS is good, really, thank you for that, but these little things make it really frustrating.

**Comment by danrabbit** [comment] 2019-10-29 16:43
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2019-10-29 16:43 UTC
