### ISSUE TITLE
Panthon-Mail crashing when opening PayPal AGB notification

### ISSUE THREAD

**Issue by Silberling** [elementary/mail#176] opened 2017-11-16 03:31 UTC
Crash when opening the PayPal AGB change notification

I open the mail, see the mail for less than a second, then, pantheon-mail crashes.

	[deb] 04:39:04 9,826910 app-email-store.vala:160: EmailStore Gmail:HIDDENEMAILADDRESS@googlemail.com running GearyAppListOperation on 1 emails
	[deb] 04:39:04 0,018203 geary-controller.vala:2661: Error checking for what operations are supported in the selected conversations: Operation was cancelled
	[deb] 04:39:04 0,002145 app-email-store.vala:182: EmailStore opening Gmail:HIDDENEMAILADDRESS@googlemail.com:INBOX (open_count=2 remote_opened=true) for GearyAppListOperation on 1 emails
	[deb] 04:39:04 0,000021 imap-engine-minimal-folder.vala:543: Not opening Gmail:HIDDENEMAILADDRESS@googlemail.com:INBOX (open_count=3 remote_opened=true): already open
	[deb] 04:39:04 0,009450 app-email-store.vala:193: EmailStore closed Gmail:HIDDENEMAILADDRESS@googlemail.com:INBOX (open_count=2 remote_opened=true) after GearyAppListOperation on 1 emails
	[deb] 04:39:04 0,000166 app-email-store.vala:219: EmailStore Gmail:HIDDENEMAILADDRESS@googlemail.com done running GearyAppListOperation on 1 emails
	[deb] 04:39:04 0,193938 ConversationWidget.vala:213: Failed get URL: Not Found
	[deb] 04:39:04 0,083173 app-email-store.vala:160: EmailStore Gmail:HIDDENEMAILADDRESS@googlemail.com running GearyAppMarkOperation on 1 emails
	[deb] 04:39:05 0,212527 app-email-store.vala:182: EmailStore opening Gmail:HIDDENEMAILADDRESS@googlemail.com:INBOX (open_count=2 remote_opened=true) for GearyAppMarkOperation on 1 emails
	[deb] 04:39:05 0,000015 imap-engine-minimal-folder.vala:543: Not opening Gmail:HIDDENEMAILADDRESS@googlemail.com:INBOX (open_count=3 remote_opened=true): already open
	[deb] 04:39:05 0,005681 app-email-store.vala:160: EmailStore Gmail:HIDDENEMAILADDRESS@googlemail.com running GearyAppMarkOperation on 1 emails
	[deb] 04:39:05 0,000665 app-email-store.vala:160: EmailStore Gmail:HIDDENEMAILADDRESS@googlemail.com running GearyAppMarkOperation on 1 emails

	(pantheon-mail:11592): Gtk-WARNING **: drawing failure for widget 'StylishWebView': invalid value (typically too big) for the size of the input (surface, pattern, etc.)

	(pantheon-mail:11592): Gtk-WARNING **: drawing failure for widget 'GtkGrid': invalid value (typically too big) for the size of the input (surface, pattern, etc.)

	(pantheon-mail:11592): Gtk-WARNING **: drawing failure for widget 'GtkGrid': invalid value (typically too big) for the size of the input (surface, pattern, etc.)

	(pantheon-mail:11592): Gtk-WARNING **: drawing failure for widget 'GtkRevealer': invalid value (typically too big) for the size of the input (surface, pattern, etc.)

	(pantheon-mail:11592): Gtk-WARNING **: drawing failure for widget 'GtkGrid': invalid value (typically too big) for the size of the input (surface, pattern, etc.)

	(pantheon-mail:11592): Gtk-WARNING **: drawing failure for widget 'ConversationWidget': invalid value (typically too big) for the size of the input (surface, pattern, etc.)

	(pantheon-mail:11592): Gtk-WARNING **: drawing failure for widget 'GtkListBox': invalid value (typically too big) for the size of the input (surface, pattern, etc.)

	(pantheon-mail:11592): Gdk-ERROR **: The program 'pantheon-mail' received an X Window System error.
	This probably reflects a bug in the program.
	The error was 'BadAlloc (insufficient resources for operation)'.
	  (Details: serial 696339 error_code 11 request_code 53 (core protocol) minor_code 0)
	  (Note to programmers: normally, X errors are reported asynchronously;
	   that is, you will receive the error a while after causing it.
	   To debug your program, run it with the GDK_SYNCHRONIZE environment
	   variable to change this behavior. You can then get a meaningful
	   backtrace from your debugger if you break on the gdk_x_error() function.)
	Trace/breakpoint trap (core dumped)

If there is any way to help, let me know how I can contribute. If there is any way to get more information that might help you just tell me.

pantheon-mail/xenial,now 1.0.6+r2349+pkg15+r1~ubuntu0.4.1.1 amd64

**Comment by mdh34** [comment] 2018-05-28 17:07
Closed as a duplicate of #27

**Closed by mdh34** 2018-05-28 17:07 UTC
