### ISSUE TITLE
Deleting single accounts is not possible

### ISSUE THREAD

**Issue by uncertainquark** [elementary/mail#212] opened 2018-05-09 05:44 UTC
If there is only one account in the Mail app, the delete account button is disabled i.e. it is not possible to delete accounts if only one is remaining.
![mail](https://user-images.githubusercontent.com/22585732/39797523-0a0086a8-537a-11e8-993a-dd9895a2ade3.png)

**Comment by danrabbit** [comment] 2018-10-17 15:55
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2018-10-17 15:55 UTC

**Comment by matej-marcisovsky** [comment] 2019-02-04 12:51
@danrabbit Current version of Mail app in Juno is the new from-scratch rewrite? If it is this issue is still there. If it is not, where is code for new Mail app?
