### ISSUE TITLE
Mail forgets passwords [$15]

### ISSUE THREAD

**Issue by thomasazar** [elementary/mail#32] opened 2017-05-31 11:36 UTC
A couple of days ago, Mail prompted me for the password to one of my Gmail accounts. I have two-factor authentication set up for all my Gmail accounts, so I used a one-time generated app password for Mail. Just as a precaution, I decided to remove all three of my Gmail accounts and re-add them, using new app passwords.

This morning, Mail once again asked for my password, for two different accounts. As they were generated a few days ago, I no longer have access to them. After hitting "Cancel", those particular Gmail accounts were removed from my Inboxes.

I'm not sure how to go about figuring out why Mail has forgotten my passwords. Both accounts that were removed this morning had been sending and receiving mail just fine in this past few days.

**Comment by Djaler** [comment] 2017-05-31 12:50
I can confirm this bug

**Comment by rene453** [comment] 2017-06-02 21:55
This is a very old issue which started with yahoo for me like 6 months ago. But i thought its a problem of yahoo as they are going through massive change or something related to api.

**Comment by btkostner** [comment] 2017-06-02 22:45
This just recently started happening with my Google accounts. As far as I know, there are no changes to the Google API.

**Comment by cassidyjames** [comment] 2017-07-01 06:08
I've had this happen to me with a Google account in the past, but am not sure how to reproduce. It might be that a token expires after some long time?

**Comment by malpaw** [comment] 2017-07-01 18:07
I don't think it expires. I noted down my token and used it again when it was "forgotten" again, and it worked fine.

**Comment by nevillepark** [comment] 2017-07-03 18:01
I also experience this bug (with my Google account). It seems to happen at random…

**Comment by btkostner** [comment] 2017-07-03 18:02
I also don't think it expires. I've had it prompt me a day after I entered a new one.

**Comment by jendamarek** [comment] 2017-07-06 13:41
I experience this bug also with my school account that I connect to with IMAP/SMTP. So I think it's not just related to Google etc.

**Comment by thepieterdc** [comment] 2017-07-08 09:29
I also experience this bug using Gmail. I had saved this one-time password somewhere and when mail forgot it, I re-entered it and it worked fine, so it didn't expire. I also don't think it's meant to expire anyways.

**Comment by Alexander-Wilms** [comment] 2017-08-02 00:22
Could be related to https://bugzilla.redhat.com/show_bug.cgi?id=1340203

**Comment by tatsuhirosatou** [comment] 2018-08-06 21:27
I had this bug on elementary Mail but on Geary it has never surfaced.

**Comment by thepieterdc** [comment] 2018-08-06 21:39
I have yet to face the bug in 2018 so far, it might be fixed?

**Comment by nevillepark** [comment] 2018-08-19 22:29
Damn! It has definitely happened to me this year, but I didn't keep track of when.

Will keep watching.

**Comment by danrabbit** [comment] 2018-10-17 22:16
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2018-10-17 22:16 UTC
Labels: Bounty, Priority: High, Status: Confirmed

**Comment by thomasazar** [comment] 2018-10-19 17:45
Fantastic news about closing this bug and the rewrite of Mail. Is the rewritten version going to be available for Juno?

**Comment by danrabbit** [comment] 2018-10-19 19:01
@thomasazar That's the goal, but there's no set timeline. It'll depend on how quickly we can get the work done

**Comment by stobbsm** [comment] 2019-09-27 20:51
This is still an issue in the current build of Juno. Every time I try to use mail, I get badgered with password dialogues every minute or so.

It's  getting and sending mail, but is pretty much unusable in this state. What information can I provide to hep track this down?
