### ISSUE TITLE
Rezise bug

### ISSUE THREAD

**Issue by eliocamp** [elementary/mail#208] opened 2018-04-23 13:40 UTC
As of yesterday I cannot' resize pantheon-mail. Dragging the border just made it wide and skinny (see picture) and neither double clicking the title bar nor using super + up maximise the window. Right now, I cannot use the application. 

![image](https://user-images.githubusercontent.com/8617595/39130195-e33db070-46e2-11e8-9887-8cf68a5c7ba3.png)

**Comment by danrabbit** [comment] 2018-04-23 15:48
Closing as a duplicate of #1

**Closed by danrabbit** 2018-04-23 15:48 UTC
