### ISSUE TITLE
Mail starts with an ugly black frame

### ISSUE THREAD

**Issue by Hilyxx** [elementary/mail#369] opened 2019-03-02 09:15 UTC
When starting the computer with new pantheon session, Mail is launched with an ugly and persistent black frame.
I have to kill pantheon-mail process to start Mail properly.

Elementary os JUNO
Mail version 1.0.8

![capture d ecran du 2019-03-02 09 39 34](https://user-images.githubusercontent.com/21991448/53679938-066c3980-3cd4-11e9-95a1-8e7d114b6d71.png)

**Comment by danrabbit** [comment] 2019-03-02 19:41
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2019-03-02 19:41 UTC
