### ISSUE TITLE
IMAP account not usable because of required @domain.name

### ISSUE THREAD

**Issue by VisioFX** [elementary/mail#132] opened 2017-08-08 10:16 UTC
Sadly I'm unable to use Mail program from Elementary OS, as the IMAP mail server
account I'm using does not have any domain name in its username.

If there is any workaround where I can set it up manually then please let me know.

**Comment by josephholsten** [comment] 2017-11-09 22:05
I hope this would no longer be an issue after the rewrite to the EDS backend.

**Comment by danrabbit** [comment] 2018-10-22 22:46
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2018-10-22 22:46 UTC
