### ISSUE TITLE
Mail account passwords longer than 46 characters are not accepted

### ISSUE THREAD

**Issue by williamscody** [elementary/mail#554] opened 2021-03-21 07:00 UTC
## What Happened
Attempted to create a Gmail account.  I could not enter my password which is 50 characters long.

## Expected Behavior
Password should have been accepted.

## Steps to Reproduce

1. Click on settings
2. Click on accounts
3. Click on + to add new account
4. Select Gmail
5. Enter account information.  Witness that in password field, cursor stops after 46 characters

### Logs
N/A

## Platform Information
elementary OS 5.1.7 Hera
Mail 1.0.8

**Comment by danrabbit** [comment] 2021-05-04 20:24
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2021-05-04 20:24 UTC
