### ISSUE TITLE
"To" field doesn't show all recipients 

### ISSUE THREAD

**Issue by eliocamp** [elementary/mail#158] opened 2017-10-06 14:33 UTC
When receiving a mail with several recipients, Mail only shows one line and there's no apparent way of expanding it to show every one. 

![issue](https://i.imgur.com/4PWeeyT.png)

**Comment by danrabbit** [comment] 2019-06-11 00:25
Closing as a duplicate of #198

**Closed by danrabbit** 2019-06-11 00:25 UTC
