### ISSUE TITLE
Place the (-) icon next to the individual address on "Additional email addresses..." panel 

### ISSUE THREAD

**Issue by josephholsten** [elementary/mail#172] opened 2017-11-09 21:43 UTC
On the "Additional email addresses..." panel, I could not tell what the crazy wide bar with the smaller black bar was. Oh! It's for removing emails from the list. I'm not sure if it's a HIG violation, but it's certainly confusing.

Less confusing might be:
- a button with icon like :no_entry: next to each list item

Bonus points for removing the **Save** button from the panel and adding **Undo** instead.

**Comment by danrabbit** [comment] 2018-10-17 15:59
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2018-10-17 15:59 UTC
