### ISSUE TITLE
Mail closes when trying to open one specific email

### ISSUE THREAD

**Issue by Kaput1982** [elementary/mail#284] opened 2018-10-20 19:17 UTC
I get a tar backup confirmation email once a day from one of my servers.  It is a simple text email that lists the output of the tar command.  If I try and open the email Mail crashes.  I tried to right click and delete the email, but the email still appears in the right pane and Mail crashes.  I don't get any error messages in the GUI.

This is what shows up in /var/log/syslog

The program 'pantheon-mail' received an X Window System error.#012This probably reflects a bug in the program.#012The error was 'BadAlloc (insufficient resources for operation)'.#012  (Details: serial 40102 error_code 11 request_code 53 (core protocol) minor_code 0)#012  (Note to programmers: normally, X errors are reported asynchronously;#012   that is, you will receive the error a while after causing it.#012   To debug your program, run it with the GDK_SYNCHRONIZE environment#012   variable to change this behavior. You can then get a meaningful#012   backtrace from your debugger if you break on the gdk_x_error() function.)

I'm running EOS Juno 64bit.  I did a clean install about two days ago.

**Comment by danrabbit** [comment] 2018-10-22 16:02
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2018-10-22 16:02 UTC

**Comment by jgomer2001** [comment] 2020-07-23 14:37
The problem persists in Elementary 5.1.4 Hera. This issue should be re-opened (there are several "duplicated" issues being open regarding the badalloc problem). Sadly I resorted to webmail after a couple of happy months mail usage.

**Comment by cassidyjames** [comment] 2020-08-12 22:14
@jgomer2001 The previous comment still applies.

>We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base.
