### ISSUE TITLE
Default avatar is cropped

### ISSUE THREAD

**Issue by ryanleesipes** [elementary/mail#49] opened 2017-07-06 23:14 UTC
![screenshot from 2017-07-06 17-05-35](https://user-images.githubusercontent.com/2141621/27936555-781e9128-626e-11e7-9ad3-511f28676f6e.png)

The above pic is set for all senders who don't have one associated with their Email address. What is it?

**Comment by danrabbit** [comment] 2017-07-06 23:15
This is likely a bug in Pop not supplying correct icon sizes. Can you reproduce this with elementary icons?

**Comment by davidmhewitt** [comment] 2017-07-06 23:16
Could also be related to https://github.com/elementary/granite/pull/75 if not built against the latest version of granite.

**Comment by ryanleesipes** [comment] 2017-07-06 23:21
Interesting, when I move to my HiDPI display (on multi-monitor setup) this shows up properly. I believe I am using the elementary icons (they are installed AFAIK).

**Comment by cassidyjames** [comment] 2017-07-06 23:23
@ryanleesipes pop-icons provide avatar icons; we might just not have an icon size specified, and Pop's is larger?

**Comment by danrabbit** [comment] 2017-07-06 23:31
This is how it looks on elementary OS ![screenshot from 2017-07-06 16 31 36](https://user-images.githubusercontent.com/7277719/27936969-9a63bcb4-6268-11e7-9dca-d6102ec839d9.png)

**Comment by danrabbit** [comment] 2019-06-11 00:08
Gonna close this since we can't reproduce it in the latest Mail

**Closed by danrabbit** 2019-06-11 00:08 UTC
Labels: Status: Incomplete
