### ISSUE TITLE
Can't login after enabling 2FA on Google account

### ISSUE THREAD

**Issue by Appeltabak** [elementary/mail#129] opened 2017-08-07 10:39 UTC
When I started Mail after enabling 2FA on my Google account I was asked to fill in my password, but it won't let me in. Instead it prompt for my password again. 

Secondly, I can't disconnected that account from Mail because the app closes when cancel the login modal.

**Comment by mohansharma-me** [comment] 2017-09-06 02:21
Hello,
I think after enabling 2FA, you should create App Password from Google My Account page and try to login with that not with your original password as Google doesn't allow basic password on "less secure apps".

**Comment by danrabbit** [comment] 2018-10-22 22:46
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2018-10-22 22:46 UTC
