### ISSUE TITLE
POP3 support

### ISSUE THREAD

**Issue by fredddii** [elementary/mail#44] opened 2017-06-30 08:25 UTC
I have always wished for POP3 to be supported. I do not want any interaction with my mail server besides grabbing the mail and then not keeping it on the server.

This is what POP3 allows. Hopefully it will be supported sometime soon.

**Comment by cassidyjames** [comment] 2017-07-01 05:59
Right now Mail uses its own IMAP back-end to communicate with servers, which is why it's IMAP-only. There is some very, very early work on porting to an Evolution Data Server back-end which would potentially allow POP3 support as well.

I can pretty safely say we're not going to engineer a custom POP3 back-end, so I'm considering this blocked by EDS for now.

**Comment by fredddii** [comment] 2017-07-01 06:02
That is unfortunate. I am in love with the simplicity of this client. But that is my only bother.

Thank you for the information.

**Comment by cassidyjames** [comment] 2017-07-01 06:15
No worries! Hopefully #15 will be solved and this will be a feature we get for free.

**Comment by danrabbit** [comment] 2018-10-17 22:15
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2018-10-17 22:15 UTC
Labels: Priority: Wishlist, Rewrite, Status: Blocked, Status: Confirmed

**Comment by eljefuri** [comment] 2018-11-10 11:57
I am 100% with @fredddii and glad to hear that this is coming with the rewrite.
