### ISSUE TITLE
Crash when loading certain emails

### ISSUE THREAD

**Issue by markfazolin** [elementary/mail#418] opened 2019-09-16 11:21 UTC
Bom dia.

Estou utilizando o programa de email, com minha conta do yahoo mail, mas quando abro alguns emails o programa é encerrado sozinho.
Parece que é quando tem imagens externas sendo mostradas.

Obrigado pela atenção.

Mark Fazolin

---

_Translation:_

>Good day.
>
>I am using the email program with my Yahoo mail account, but when I open some emails the program quits on its own. It seems to be when there are external images being shown.
>
>Thanks for listening.
>
>Mark Fazolin

**Comment by tvdeyen** [comment] 2019-10-11 14:37
I have the same problems with emails from various senders (PayPal recently). Most of the time these are rich HTML e-mails. Having these problems with two different accounts. Gmail and a IMAP account from a open exchange server.

This is from my SysLog:

```
Oct 11 16:30:27 tvd-eos pantheon-mail[25078]: Could not load a pixbuf from icon theme.#012This may indicate that pixbuf loaders or the mime database could not be found.
Oct 11 16:30:34 tvd-eos pantheon-mail[25078]: The program 'pantheon-mail' received an X Window System error.#012This probably reflects a bug in the program.#012The error was 'BadAlloc (insufficient resources for operation)'.#012  (Details: serial 37388 error_code 11 request_code 53 (core protocol) minor_code 0)#012  (Note to programmers: normally, X errors are reported asynchronously;#012   that is, you will receive the error a while after causing it.#012   To debug your program, run it with the GDK_SYNCHRONIZE environment#012   variable to change this behavior. You can then get a meaningful#012   backtrace from your debugger if you break on the gdk_x_error() function.)
Oct 11 16:30:34 tvd-eos kernel: [117218.808101] traps: pantheon-mail[25078] trap int3 ip:7f6909d23ea1 sp:7ffdbe3aca10 error:0 in libglib-2.0.so.0.5600.4[7f6909cd2000+114000]
```

Loading the mail on Mail.app on my mac or iPhon works, but constantly crash on Pantheon Mail. They even successfully load on Evolution.

If you need anything else on information, please tell me.

This is the latest version of Mail (can't actually tell the version as there is no "About" window in this App)

**Comment by ryonakano** [comment] 2019-10-11 14:47
Judging from the log, this looks a duplicate of #417

**Comment by tvdeyen** [comment] 2019-10-11 15:26
Yeah, seems like it, but since #417 seems like a duplicate of #407 and the above mentioned email is not a long conversation (its just one mail) it maybe isnt? But related. Somehow long emails or lots of emails on one conversation causing crashes. I can verify that I have also lots of problems with emails having long conversations, like emails from discussion boards (zendesk and like).

**Comment by markfazolin** [comment] 2023-06-20 17:46
I don't use Pantheon Mail anymore.

**Closed** 2023-06-20 17:45 UTC
Labels: v1.0
