### ISSUE TITLE
Accounts configuration height unsizable

### ISSUE THREAD

**Issue by rafaelcn** [elementary/mail#161] opened 2017-10-31 12:47 UTC
I have an account with another service configured and the size of the account configuration dialog is to big to fit on the screen, I can't configure my signature properly. It should be resizable or it should have at least a scroll bar. Below is an image depicting the problem:

![screenshot from 2017-10-31 10 38 21](https://user-images.githubusercontent.com/3271143/32224561-19a725b2-be29-11e7-943f-c61d470ea016.png)

**Comment by danrabbit** [comment] 2018-10-17 16:02
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2018-10-17 16:02 UTC

**Comment by Davide95** [comment] 2019-02-13 19:13
Hey @danrabbit, are there news about it? 
The problem still persist after more than one year

**Comment by SamBrishes** [comment] 2020-02-22 08:53
Hellow,

any update about this, because the error is still there?

![mail-error](https://user-images.githubusercontent.com/31392477/75089440-0dc9ca00-5559-11ea-80c9-05f530094424.png)

Thanks!
