### ISSUE TITLE
Mail crashes instantly after starting

### ISSUE THREAD

**Issue by metd34** [elementary/mail#535] opened 2021-01-02 22:42 UTC
For about the last 10 days, Mail crashes in less than a second after starting. 

I uninstalled and reinstalled but it did not help. 

Please see the attached video.

https://user-images.githubusercontent.com/19665300/103467917-e9d43900-4d64-11eb-8047-a55b7254b0f7.mp4

Thank you.

PS: gdb did not return any results.

**Comment by danrabbit** [comment] 2021-01-05 19:37
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue very likely no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2021-01-05 19:37 UTC
