### ISSUE TITLE
POP Protocol Support

### ISSUE THREAD

**Issue by bg15407** [elementary/mail#186] opened 2018-01-27 17:09 UTC
Hi

I cannot add my POP mail 

pls fix this issue since my workplace using the pop

Thanks

**Comment by danrabbit** [comment] 2018-10-17 22:11
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2018-10-17 22:11 UTC
