### ISSUE TITLE
Autocomplete recipients using known addresses

### ISSUE THREAD

**Issue by thefirstofthe300** [elementary/mail#743] opened 2021-12-18 10:17 UTC
### Problem

Seems fairly self-explanatory. I have contacts. I'm currently not really given any mechanism to manage those contacts.

### Proposal

I'd like to be able to manage contacts using some form of app. Maybe not integrated into Mail though since contacts could be used in the calendar invites, for example.

Also, Mail should be able to autocomplete my recipients in the To, CC, and BCC fields using aforementioned contacts.

**Comment by marbetschar** [comment] 2021-12-20 08:32
There is a contact management app in the works which is called "Friends". Not sure what the current state there is though:
https://github.com/elementary/friends

We can still keep this issue here open, cause of:

> Mail should be able to autocomplete my recipients in the To, CC, and BCC fields using aforementioned contacts.

**Comment by danrabbit** [comment] 2021-12-21 22:27
Hm, unless something happened this should have been fixed in https://github.com/elementary/mail/pull/123

**Comment by vipranarayan14** [comment] 2022-01-16 13:57
I am using Elementary OS for the past two months. I have tried composing new emails in the Mail app several times. I do not get autocomplete for contact addresses. It is very frustrating. I had to use a different app or the Gmail website for sending emails. Please fix this.

**Comment by marbetschar** [comment] 2022-01-18 07:37
I can confirm; autocompletion never worked on my end in the new Mail. @danrabbit I guess for this to work some sort of contact sync must be setup (which Online Accounts does not officially support yet)?

Wouldn't it be better to primarily use addresses available in Mail?  And if there's no match, fall back to external sources such as stored contacts. Or whats the reasoning for a stored contacts only approach?

**Comment by janxkoci** [comment] 2022-03-14 19:07
I updated to OS 6.1 last week, today was the first workday with the new setup. Long story short, I installed Geary after lunch, because Mail still misses too many things (at one point I've sent a reply to an email chain from an account that was not even in the chain - still puzzled by that). Geary autocompleted my contacts right away without problems, the same way the old version of Mail did.

**Are bounties still a thing?** I would gladly pay to have Mail up and running again. I can live with Geary for now, but it's UX did some design choices I don't really agree with. Also dark mode doesn't work for some reason.

**Comment by danrabbit** [comment] 2022-04-05 18:44
@marbetschar I think ideally using folks should automatically aggregate contacts from all EDS sources, so we wouldn't need to implement multiple contacts backends. It sounds like from talking to @tintou before though that it might be better to use EDS directly to get contacts from any connected accounts?

**Comment by janxkoci** [comment] 2023-09-08 09:32
I'd like to bump this into the spotlight again, it is now the main roadblock preventing me to use Mail in any serious capacity.

After update to OS 7, **Geary** is no longer working for me (I cannot setup any account, I suspect I'm missing some component but couldn't find anything on Flathub). At the moment I'm using **Mailspring**, which does work as I expect, but it stands out like sore thumb. I'd also prefer a native app over Electron.

Is there any progress on the autocomplete functionality? And how does the Evolution client handle this? Can the logic be reused?

**Comment by leolost2605** [comment] 2023-09-09 17:49
Oh right I forgot to mention this issue in #927 but that PR should be the fix for this.

**Comment by janxkoci** [comment] 2023-09-10 09:04
That's great! It seems to only be a partial fix though, as it will only autocomplete addresses I used. The problem is it's currently hard to use existing addresses, as we basically need to copy-paste them from somewhere first. Other mail clients like Geary have autocomplete working from start without any extra steps.

But it's great to hear there is some progress! 🙂

**Closed** 2023-11-11 05:56 UTC
Labels: Status: Confirmed
