### ISSUE TITLE
Folders view is not saving. Always need to make it wide

### ISSUE THREAD

**Issue by xplore93** [elementary/mail#428] opened 2019-10-11 09:47 UTC
## Prerequisites
- [ ] I have searched open and closed issues for duplicates.

## Describe the bug

If applicable, add screenshots or screen recordings to help explain your problem.

## Platform Information

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by ryonakano** [comment] 2019-10-11 10:08
![screenshot from 2018-11-10 16-02-57](https://user-images.githubusercontent.com/26003928/48298543-85115100-e502-11e8-8d5f-ac8d6ecc0836.png)

@xplore93 Do you mean that the width of the left sidebar is not saved and you need to adjust its width every time you launch the Mail app?

**Comment by xplore93** [comment] 2019-10-11 10:09
Yes, that is what I mean.

**Comment by ryonakano** [comment] 2019-10-11 10:15
OK, then I'll close this as a duplicate of #427. This issue seems to be fixed in the latest version of Mail (which has not been released yet). I apologize for the inconvenience, hope you would be patient until the new version is released.

But thank you for your reporting!

**Comment by xplore93** [comment] 2019-10-11 10:16
Thank you! And sorry for duplicate. Have a nice day

**Closed by ryonakano** 2019-10-11 10:15 UTC
