### ISSUE TITLE
Authentication gone wrong, can't reset mail to start clean.

### ISSUE THREAD

**Issue by kvdz** [elementary/mail#365] opened 2019-02-20 19:25 UTC
Because mail can't authenticate my work email anymore due to server changes.
It promps the authentication dialog when i fill it in 2 times, mail crashes.
I am not able to change any settings before the crash, this makes mail client unusable for me.

I have no ability to reset mail to a clean state (delete email accounts) via terminal or in the GUI.

**Comment by danrabbit** [comment] 2019-02-23 09:03
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2019-02-23 09:03 UTC
