### ISSUE TITLE
Email window size

### ISSUE THREAD

**Issue by Chamrosh** [elementary/mail#378] opened 2019-05-07 09:09 UTC
The size of the software window is not fixed, after the system restarts, the window changes to the maximum possible

![Screenshot from 2019-05-07 13 37 25](https://user-images.githubusercontent.com/10561726/57287728-6533a200-70cd-11e9-8686-7a712481d702.png)
![Screenshot from 2019-05-07 13 37 37](https://user-images.githubusercontent.com/10561726/57287730-6664cf00-70cd-11e9-8360-ab1dd032cdd1.png)

**Comment by danrabbit** [comment] 2019-06-06 17:08
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2019-06-06 17:08 UTC
