### ISSUE TITLE
Mails not rendered properly

### ISSUE THREAD

**Issue by TomiOhl** [elementary/mail#968] opened 2023-10-26 15:32 UTC
### What Happened?

In the past two weeks, mails don't get rendered properly - only parts of them are: 
![image](https://github.com/elementary/mail/assets/6696659/47d27775-d60b-4e3d-8a98-9e4e4073cc23)
Note that this changes by scrolling, i.e. if you scroll you might see more or less.
I've updated Mail to the latest release at the time it was released, so like 2 months before the issue started to appear. This might mean the issue is not actually in Mail but in some external dependency (webview-related?)

### Steps to Reproduce

1. Install all updates to the system
2. Open some mails

### Expected Behavior

All mails should be rendered properly

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

### Hardware Info

I'm getting the issue on two machines with different hw (intel + nvidia and ryzen 7), so probably not hw-related

**Comment by jeremypw** [comment] 2023-10-26 17:08
Duplicate of #950?

**Comment by TomiOhl** [comment] 2023-10-27 11:05
Hmm yes, probably it'st the same, just different wording. Feel free to close this in this case

**Comment by jeremypw** [comment] 2023-10-27 16:17
Closing as duplicate of #950

**Closed by jeremypw** 2023-10-27 16:17 UTC
Labels: Status: Confirmed
