### ISSUE TITLE
How many email services should have defaults?

### ISSUE THREAD

**Issue by josephholsten** [elementary/mail#168] opened 2017-11-09 01:12 UTC
I think we should definitely add defaults for iCloud (and probably yandex & qq), but I'm wondering how many other services should have defaults.

I'm especially partial to FastMail/Pobox. They seem spiritually similar to elementary: they believe that free isn't as sustainable as paid, and contribute significantly to many open source IMAP (&c) service codebases.

But at what point are we overloading the user? I know that I don't want a scrollbar in the dropdown selector. But I guess the service selector could be less terrible than X-Chat's network selector by using a fuzzy filter.

**Comment by danrabbit** [comment] 2018-10-17 16:00
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2018-10-17 16:00 UTC
