### ISSUE TITLE
deleting email account

### ISSUE THREAD

**Issue by JO0st** [elementary/mail#178] opened 2017-12-21 10:40 UTC
I have multiple accounts configured in pantheon-mail, and need to delete one of them. When the accout is deleted everything works as it should, however when the program is closed and reopened it asks for the password of the deleted account.

Pantheon-mail crashes when I don't enter a password, and keeps asking for a password until I enter the correct one.

I allready checked the ~/.local/share/pantheon-mail folder and the account folder is deleted on deleting the account. However it is recreated when pantheon-mail is closed and reopened.

**Comment by danrabbit** [comment] 2018-10-17 15:58
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2018-10-17 15:58 UTC
