### ISSUE TITLE
Can't change account settings

### ISSUE THREAD

**Issue by jtrees** [elementary/mail#174] opened 2017-11-15 08:49 UTC
#### Steps to Reproduce
1. Create a new account with an arbitrary config
2. Open the account view
3. Go to the edit view for the created account

#### Expected Result
Fields such as "Server" and "Username" should be editable.

#### Actual Result
Only the "Nickname" and "Password" fields are editable.

**Comment by danrabbit** [comment] 2018-10-17 15:58
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2018-10-17 15:58 UTC

**Comment by jtrees** [comment] 2018-10-18 08:33
Sound great! Will the new version of Mail become available as an update for Juno or will we have to wait for elementaryOS 6?

**Comment by danrabbit** [comment] 2018-10-18 21:17
@jtrees It depends on how long it takes to complete. The most optimal situation would be to deliver it as an update, but only time will tell if that's realistic
