### ISSUE TITLE
App crashes 2-3 seconds after opening

### ISSUE THREAD

**Issue by TechLabsUS** [elementary/mail#560] opened 2021-04-13 01:56 UTC
On a StarLabs Linux notebook running ElementaryOS...
Within the last couple of days the mail app crashes every time it's opened.  It briefly displays the inbox before crashing.  Below is the entry from my syslog.

The program 'pantheon-mail' received an X Window System error.#012This probably reflects a bug in the program.#012The error was 'BadAlloc (insufficient resources for operation)'.#012  (Details: serial 6379 error_code 11 request_code 53 (core protocol) minor_code 0)#012  (Note to programmers: normally, X errors are reported asynchronously;#012   that is, you will receive the error a while after causing it.#012   To debug your program, run it with the GDK_SYNCHRONIZE environment#012   variable to change this behavior. You can then get a meaningful#012   backtrace from your debugger if you break on the gdk_x_error() function.)

traps: pantheon-mail[5967] trap int3 ip:7fb9727b1fc1 sp:7ffe6c63c510 error:0 in libglib-2.0.so.0.5600.4[7fb972760000+114000]

**Comment by meisenzahl** [comment] 2021-04-13 13:56
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue very likely no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by meisenzahl** 2021-04-13 13:56 UTC
