### ISSUE TITLE
Mail doesn't wait for unlocking the keyring

### ISSUE THREAD

**Issue by jendamarek** [elementary/mail#217] opened 2018-05-22 17:50 UTC
I use autologin on my computer. When the system loads, there are 3 password dialogs, one for unloking the keyring and the other 2 for my mail accounts. If the keyring is locked, Mail should not ask for passwords until the keyring is unlocked or the Mail app is run by the user. Otherwise its really annoying.

**Comment by danrabbit** [comment] 2018-10-22 22:42
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2018-10-22 22:42 UTC
