### ISSUE TITLE
Horribly large window size

### ISSUE THREAD

**Issue by WattanaGaming** [elementary/mail#272] opened 2018-10-18 16:24 UTC
![screenshot from 2018-10-18 23-23-13](https://user-images.githubusercontent.com/25323231/47169124-e6436b80-d32c-11e8-9703-7c1615cb138f.png)

**Comment by danrabbit** [comment] 2018-10-18 16:28
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2018-10-18 16:28 UTC

**Comment by WattanaGaming** [comment] 2018-10-18 16:42
When is the new version will come?

**Comment by danrabbit** [comment] 2018-10-18 19:44
@WattanaGaming there is no timeline. As soon as it can, but no sooner :)
