### ISSUE TITLE
mail deserialize error

### ISSUE THREAD

**Issue by Ikki-Dai** [elementary/mail#366] opened 2019-02-24 05:34 UTC
Hi, 
while add account and debug logs show as below, so can't add mail account failed 

 [deb] 13:27:10 76.697653 imap-client-session.vala:1455: [0000/imap.*****.com/default:993 GEARY_IMAP_CLIENT_SESSION_STATE_CONNECTING] Connected to imap.*****.com/default:993
 [deb] 13:27:10 0.000002 imap-client-session.vala:624: [0000/imap.*****.com/default:993 GEARY_IMAP_CLIENT_SESSION_STATE_CONNECTING] Connected
13:27:10 0.000413 imap-deserializer.vala:487: Attempt to close unopened list/response code
 [deb] 13:27:10 0.000010 imap-client-session.vala:1610: [0000/imap.*****.com/default:993 GEARY_IMAP_CLIENT_SESSION_STATE_CONNECTING] Receive failed: Unable to deserialize from 0000//**.**.**.**:993/GEARY_IMAP_CLIENT_CONNECTION_STATE_CONNECTED
 [deb] 13:27:10 0.000002 imap-client-session.vala:1297: [0000/imap.*****.com/default:993 GEARY_IMAP_CLIENT_SESSION_STATE_CONNECTING] Connecting send/recv error, dropping client connection: Unable to deserialize from 0000/**.**.**.**:993/GEARY_IMAP_CLIENT_CONNECTION_STATE_CONNECTED

**Comment by danrabbit** [comment] 2019-02-24 05:58
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2019-02-24 05:58 UTC
