### ISSUE TITLE
Mail Accounts Duplicaton

### ISSUE THREAD

**Issue by TwentyOneSpokes** [elementary/mail#764] opened 2022-01-29 06:59 UTC
### What Happened?

When opening the Mail app my Google Accounts and associated inboxes were duplicated. If the app was closed and re-opened an additional duplication appeared. The issue was resolved when the app appeared to 'crash' and when opening a further time the expected number of accounts were displayed.

![image](https://user-images.githubusercontent.com/84473310/151651242-1c1b3080-3c8b-4864-a20c-8b42f74d21f8.png)

### Steps to Reproduce

Unsure on how to reliably reproduce but occurs often during an operating session.

### Expected Behavior

Only single Google Account displayed.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by TomiOhl** [comment] 2022-02-01 21:00
Can confirm. I can add that if there are already duplicated accounts, thus the combined inbox option shows up, clicking on it crashes the app.

**Comment by eczarny** [comment] 2022-02-06 02:15
I'm fairly sure the background crash fix introduced in #760 uncovered this issue: since the app would crash in the background, it would always start with a fresh `Mail.Backend.Session`. After the fix the app keeps asking the `Mail.Backend.Session` to start.

I've attempted some debugging and the first issue I noticed is that `Mail.InboxMonitor` is not using the singleton instance of `Mail.Backend.Session`. This inconsistency isn't the root cause, but it doesn't help matters. My assumption is the singleton instance should be the instance used across the entirety of the app.

What I'm trying to figure out now is why `Mail.Backend.Session` is being told to start multiple times on each launch of the app. I suspect it's due to this code, though I can't be certain:

https://github.com/elementary/mail/blob/dcfb11d11278e2201fdb34a372d39b7e657256b4/src/MainWindow.vala#L320-L324

Those lines are crucial to the UI functioning correctly, so omitting them isn't a true solution. I'll keep at it for a bit but I'm confused by how this app manages its lifecycle. I'd assume that the background process should own the inbox monitor which, in turn, starts the underlying session. When launched to the foreground the app should simply connect to the existing instances of these objects.

**Comment by marbetschar** [comment] 2022-02-06 11:17
@eczarny good detective work! I submitted a fix which follows pretty much your analysis: https://github.com/elementary/mail/pull/769

Thanks to your work I also uncovered another issue with the background process, which - for some reason - still crashes:
https://github.com/elementary/mail/issues/768

**Comment by MedLabs** [comment] 2022-02-09 20:39
I don't know if the last update comes with that fix, but the duplicated accounts are still there...
How to get rid of them ? should I delete my accounts and add them again ?

**Comment by marbetschar** [comment] 2022-02-09 20:54
@MedLabs the fix is not merged and not released yet. That said, it should make it into the next update of Mail which is probably by end of February (if everything goes according to plan).

**Comment by jalcine** [comment] 2022-04-15 15:02
This happened to me with my Fastmail account on eOS 6.1 Jolnir
![Screenshot from 2022-04-15 11 01 19](https://user-images.githubusercontent.com/452100/163586894-e60cc641-22f2-468f-a298-d84ddfd2fceb.png)

**Closed** 2022-05-16 19:52 UTC

**Comment by jalcine** [comment] 2022-06-14 17:35
This looks like it's still an issue for me as of <code>6.4.0+r1019+pkg28~ubuntu6.1.1</code> with my IMAP accounts in Fastmail.

(Originally published at: https://jacky.wtf/2022/6/5haz)
