### ISSUE TITLE
Mail crashes immedietly on opening.

### ISSUE THREAD

**Issue by TimApp1e** [elementary/mail#289] opened 2018-10-22 14:11 UTC
I tried to archive an email from my fastmail account. This crashed mail, then ever since it crashes right at startup. I tried to open it in the terminal so you could see what was going on. 

```
tim@ele-mothership:/media/tim$ pantheon-mail 

(pantheon-mail:2178): Gtk-WARNING **: 09:07:18.316: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.

(pantheon-mail:2178): Gdk-ERROR **: 09:07:18.414: The program 'pantheon-mail' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAlloc (insufficient resources for operation)'.
  (Details: serial 2739 error_code 11 request_code 53 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
Trace/breakpoint trap
```

**Comment by danrabbit** [comment] 2018-10-22 15:59
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2018-10-22 15:59 UTC

**Comment by sempasha** [comment] 2019-03-27 18:09
Hi, how long to wait new Mail will be available in AppCenter?
