### ISSUE TITLE
Account settings dialog is too long for my screen

### ISSUE THREAD

**Issue by rajkumaar23** [elementary/mail#467] opened 2020-04-08 07:52 UTC
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

Duplicate of #11 - Still the issue exists.

## Describe the bug
I'm not able to edit any configuration of any account. I don't even see the save button.

### To Reproduce
1. Go to Settings
2. Click on Edit button on any account
3. Scroll down to Composer section
4. See that nothing below the title `Composer` is visible.

### Expected behavior
I should be able to edit my signatures and **save** the settings.

### Screenshots or screen recordings
![image](https://user-images.githubusercontent.com/37476886/78758396-b4e4b280-799b-11ea-9781-79977d9b1e16.png)

## Platform Information
![image](https://user-images.githubusercontent.com/37476886/78758047-1f492300-799b-11ea-8067-254358305558.png)

Please check what applies:
-->
- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by rajkumaar23** [comment] 2020-04-08 08:10
Temporary I’m able to `Super + Drag`. But when will this issue be fixed?

**Comment by danrabbit** [comment] 2020-04-08 22:26
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2020-04-08 22:26 UTC
