### ISSUE TITLE
OWA support (MS Exchange)

### ISSUE THREAD

**Issue by ramizdemiurge** [elementary/mail#55] opened 2017-07-12 08:08 UTC
What about Outlook Web Access support? I'm talking about MS Exchange.
I like pantheon-mail, and I don't wanna use another app. Thanx.

**Comment by Buri** [comment] 2017-10-11 08:19
Any updates on this?

**Comment by jendamarek** [comment] 2018-04-27 09:46
This should be possible to work on after porting Mail to Evolution data server backend (see projects section). Until then you can use a workaround with DavMail (http://davmail.sourceforge.net/) The configuration is not much user friendly, but it works.

**Comment by danrabbit** [comment] 2018-10-22 22:45
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2018-10-22 22:45 UTC
Labels: Rewrite
