### ISSUE TITLE
Wishlist: Support for MS Exchange accounts

### ISSUE THREAD

**Issue by carniz** [elementary/mail#303] opened 2018-10-25 15:43 UTC
In short: it would be a "killer feature" (IMHO) to provide native support for MS Exchange servers. In the Linux world Thunderbird has it and the commercial Hiri client has it as well - and I've also managed to connect Evolution to an MS Exchange server using the evolution-ews plugin - but it would be nice if our native mail app had support for it as well.

**Comment by danrabbit** [comment] 2018-10-25 16:46
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2018-10-25 16:46 UTC

**Comment by carniz** [comment] 2018-10-26 07:46
> Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

Wow...should I interpret that as "the rewrite of Mail will have native support for MS Exchange servers"?

**Comment by tintou** [comment] 2018-10-26 08:05
@carniz To be more specific, we are using the same component as Evolution to build our backend, so yes afaik Evolution has support of Exchange so do we :)

**Comment by bbetter** [comment] 2019-02-07 16:54
So is it available right now in current elementary os , if no when it's going to be ?
