### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by xunilarium** [elementary/mail#389] opened 2019-06-08 10:42 UTC
Compose mail doesn't support right to left language.

**Comment by vertexian** [comment] 2019-06-09 02:49
Could you please be more specific? I tried entering some Persian text and it seemed to work fine. What isn't working as expected?

**Comment by xunilarium** [comment] 2019-06-09 06:37
As you know Persian and other RTL language are Right to Left and not Left to Right. So when you try to write Persian or combination of Persian and English:
1. It should shows on the right of the page and not left.
2. Combination of Persian and English is messy.

In Mail app:
![01](https://user-images.githubusercontent.com/10381709/59155837-99242d80-8aa6-11e9-862c-412146d68b03.png)

It should be:
![Link to 02](https://user-images.githubusercontent.com/10381709/59155851-bb1db000-8aa6-11e9-994d-088abfc4d326.png)

**Comment by danrabbit** [comment] 2019-06-10 23:50
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Comment by vertexian** [comment] 2019-06-11 00:33
@danrabbit, are you sure? I can reproduce this behavior in the development version, both in terms of left-alignment and when embedding LTR text within RTL. Only in the body, though. The text renders correctly in the subject line.

**Comment by vertexian** [comment] 2019-06-11 01:07
It looks like Geary makes it work by using `<div dir="auto"/>` in their template. I can achieve the same by adding that attribute to our template. Will submit a PR later tonight.

**Comment by danrabbit** [comment] 2019-06-11 06:07
Oops my bad. Good catch!

**Closed** 2019-06-11 06:06 UTC
