### ISSUE TITLE
Implement “Next Email” behavior

### ISSUE THREAD

**Issue by cassidyjames** [elementary/mail#368] opened 2019-02-27 22:58 UTC
Most clients have an option between progressing to the next email or showing a blank screen after deleting or archiving the focused email. Mail currently does neither, and keeps showing the deleted mail.

**Comment by andreppi** [comment] 2020-04-11 13:30
I don't think this is an issue in 5.1.3, at least I wasn't able to reproduce it after archiving/deleting a message. 
@cassidyjames, can you provide steps to reproduce? I may be able to take a look at this issue if it's still valid.

**Comment by andreppi** [comment] 2020-04-11 14:29
After further investigation it seems to be configurable. In order to show the next message automatically one has to enable it in the app settings.
![image](https://user-images.githubusercontent.com/20740857/79046490-c8448780-7c00-11ea-8746-937f76528fdd.png)

**Comment by cassidyjames** [comment] 2020-04-11 14:35
@andreppi this is for the current master branch which is a rewrite.

**Comment by andreppi** [comment] 2020-04-11 17:28
Sorry about the misunderstanding.
I was able to implement a reset conversation behavior after the delete action meaning that it'll show the screen stating "No message selected". 
Will it be useful for now?

**Comment by cassidyjames** [comment] 2020-07-24 15:33
@andreppi sorry, this got lost. Yeah, that would be helpful!

**Comment by danirabbit** [comment] 2023-07-25 22:43
We have the select next message behavior implemented now, so closing

**Closed by danirabbit** 2023-07-25 22:43 UTC
Labels: Status: Confirmed
