### ISSUE TITLE
Big empty area

### ISSUE THREAD

**Issue by Djaler** [elementary/mail#281] opened 2018-10-18 20:01 UTC
As you see in screenshot, there are big unused space below message body. This happens not always but often.

![2018-10-18 22 59 38](https://user-images.githubusercontent.com/7964583/47180588-91522600-d329-11e8-87c2-5b717783fb65.png)

**Comment by danrabbit** [comment] 2018-10-18 20:06
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2018-10-18 20:06 UTC
