### ISSUE TITLE
Mail is getting automatically bigger and bigger

### ISSUE THREAD

**Issue by ViniciusBRodrigues** [elementary/mail#242] opened 2018-09-27 11:33 UTC
Hi guys,

Today the mail app has a strange behaviour. The window was getting bigger and bigger in width. I'm sending a print screen. I have already reboot my computer and still happening.
![captura de tela de 2018-09-27 08 21 20](https://user-images.githubusercontent.com/12240167/46143210-ae666e00-c22f-11e8-9590-6b7624041952.png)

Sytem info:

```
viniciusbr@viniciusbr-K46CA:~$ uname -a
Linux viniciusbr-K46CA 4.15.0-34-generic #37~16.04.1-Ubuntu SMP Tue Aug 28 10:44:06 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
viniciusbr@viniciusbr-K46CA:~$ sudo lshw -short
[sudo] senha para viniciusbr:          
Caminho do hardware      Dispositivo  Classe         Descrição
================================================================
                                      system         K46CA (ASUS-NotebookSKU)
/0                                    bus            K46CA
/0/0                                  memory         64KiB BIOS
/0/8                                  memory         512KiB L2 cache
/0/9                                  memory         128KiB L1 cache
/0/a                                  memory         4MiB L3 cache
/0/b                                  memory         6GiB Memória do sistema
/0/b/0                                memory         4GiB SODIMM DDR3 Síncrono 1600 MHz (0,
/0/b/1                                memory         DIMMProject-Id-Version: lshwReport-Msgi
/0/b/2                                memory         2GiB SODIMM DDR3 Síncrono 1600 MHz (0,
/0/b/3                                memory         DIMMProject-Id-Version: lshwReport-Msgi
/0/c                                  processor      Intel(R) Core(TM) i7-3517U CPU @ 1.90GH
/0/100                                bridge         3rd Gen Core processor DRAM Controller
/0/100/2                              display        3rd Gen Core processor Graphics Control
/0/100/4                              generic        3rd Gen Core Processor Thermal Subsyste
/0/100/14                             bus            7 Series/C210 Series Chipset Family USB
/0/100/14/0              usb3         bus            xHCI Host Controller
/0/100/14/0/1                         input          2.4G Receiver
/0/100/14/0/3            scsi6        storage        WALKMAN
/0/100/14/0/3/0.0.0      /dev/sdc     disk           1943MB WALKMAN
/0/100/14/0/3/0.0.0/0    /dev/sdc     disk           1943MB 
/0/100/14/0/3/0.0.0/0/1               volume         463MiB W95 FAT32 partition
/0/100/14/1              usb4         bus            xHCI Host Controller
/0/100/16                             communication  7 Series/C210 Series Chipset Family MEI
/0/100/1a                             bus            7 Series/C210 Series Chipset Family USB
/0/100/1a/1              usb1         bus            EHCI Host Controller
/0/100/1a/1/1                         bus            Integrated Rate Matching Hub
/0/100/1a/1/1/1                       communication  Bluetooth USB Host Controller
/0/100/1a/1/1/3                       multimedia     USB Camera
/0/100/1b                             multimedia     7 Series/C210 Series Chipset Family Hig
/0/100/1c                             bridge         7 Series/C210 Series Chipset Family PCI
/0/100/1c.1                           bridge         7 Series/C210 Series Chipset Family PCI
/0/100/1c.1/0            wlp2s0       network        AR9485 Wireless Network Adapter
/0/100/1c.3                           bridge         7 Series/C210 Series Chipset Family PCI
/0/100/1c.3/0                         generic        RTL8411 PCI Express Card Reader
/0/100/1c.3/0.2          enp3s0f2     network        RTL8111/8168/8411 PCI Express Gigabit E
/0/100/1d                             bus            7 Series/C210 Series Chipset Family USB
/0/100/1d/1              usb2         bus            EHCI Host Controller
/0/100/1d/1/1                         bus            Integrated Rate Matching Hub
/0/100/1f                             bridge         HM76 Express Chipset LPC Controller
/0/100/1f.2                           storage        7 Series Chipset Family 6-port SATA Con
/0/100/1f.3                           bus            7 Series/C210 Series Chipset Family SMB
/0/1                     scsi0        storage        
/0/1/0.0.0               /dev/sda     disk           1TB TOSHIBA MQ01ABD1
/0/1/0.0.0/1                          volume         511MiB Windows FAT volume
/0/1/0.0.0/2             /dev/sda2    volume         925GiB volume EXT4
/0/1/0.0.0/3             /dev/sda3    volume         6028MiB Linux swap volume
/0/2                     scsi1        storage        
/0/2/0.0.0               /dev/sdb     disk           22GB SG9MSM6D024GPM00
/0/2/0.0.0/1             /dev/sdb1    volume         20GiB data partition
/0/3                     scsi2        storage        
/0/3/0.0.0               /dev/cdrom   disk           DVD-RAM UJ8C2 S
viniciusbr@viniciusbr-K46CA:~$ lscpu
Arquitetura:           x86_64
Modo(s) operacional da CPU:32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per núcleo  2
Núcleo(s) por soquete:2
Soquete(s):            1
Nó(s) de NUMA:        1
ID de fornecedor:      GenuineIntel
Família da CPU:       6
Modelo:                58
Model name:            Intel(R) Core(TM) i7-3517U CPU @ 1.90GHz
Step:                  9
CPU MHz:               1161.195
CPU max MHz:           3000,0000
CPU min MHz:           800,0000
BogoMIPS:              4789.49
Virtualização:       VT-x
cache de L1d:          32K
cache de L1i:          32K
cache de L2:           256K
cache de L3:           4096K
NUMA node0 CPU(s):     0-3
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts flush_l1d
```

**Comment by ryonakano** [comment] 2018-09-27 13:28
@ViniciusBRodrigues I suppose this is a duplication of #222 (and #1 essentially).

**Comment by danrabbit** [comment] 2018-09-27 17:43
Closing as a duplicate of #1

**Closed by danrabbit** 2018-09-27 17:43 UTC
