### ISSUE TITLE
Mail account can not be added

### ISSUE THREAD

**Issue by rhcp77** [elementary/mail#223] opened 2018-07-08 19:28 UTC
Hi,

I'd like to add an German IMAP account but without success.

The following settings are possible:

SMTP-Server 	mx.freenet.de
POP3-Server 	mx.freenet.de
IMAP-Server 	mx.freenet.de
SMTP-Authentication 	ASMTP / SMTP-Auth aktiv
SMTP-Port 	587
Encryption 	necessary (STARTTLS / TLS / SSL)

Used Ports:
    STARTTLS:
        SMTP (Delivery): 587
        IMAP (Receipt): 143
        POP3 (Receipt): 110
    SSL/TLS
        SMTP (Delivery): 587
        IMAP (Receipt): 993
        POP3 (Receipt): 995
    SMTPS
        SMTPS (Delivery): 465
        IMAP (Receipt): 993
        POP3 (Receipt): 995 

How can I setup the mail account?

Thank you in advance,
usyber

**Comment by danrabbit** [comment] 2018-10-17 22:50
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2018-10-17 22:50 UTC
