### ISSUE TITLE
Account dialog is super tall and doesn't fit on small displays

### ISSUE THREAD

**Issue by cassidyjames** [elementary/mail#11] opened 2017-04-27 15:46 UTC
Happened to several coworkers using a 13" 3200x1800 HiDPI display (so 1600x900 virtual resolution) and our company email account. Will grab a sanitized screenshot ASAP.

**Comment by cassidyjames** [comment] 2017-04-27 16:05
Here's a redacted screenshot
![pantheon-mail-accounts](https://cloud.githubusercontent.com/assets/611168/25492640/e7f6b16c-2b30-11e7-8488-71aec9e6f527.png)

**Comment by cassidyjames** [comment] 2017-04-27 16:10
Also to note: this is even worse with stylesheets that have more padding than the elementary Stylesheet, like Adwaita or Adapta.

**Comment by danrabbit** [comment] 2018-10-17 16:05
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2018-10-17 16:05 UTC
Labels: Rewrite, Status: Confirmed

**Comment by escapedsalmon** [comment] 2018-11-07 16:08
Hey!

So seeing that you say you're working on a complete new codebase. Is there any way to get this new codebase or get the new version?
'Cause on ElementaryOS 5.0 I am currently running in exactly this issue, but I haven't found a way to move the windows upwards (ALT+drag does not work for any reason?) - so I have to stick with another email client for now.

**Comment by cassidyjames** [comment] 2018-11-07 16:32
@escapedsalmon it is not currently at feature parity, but it's being actively developed. We'll announce on our blog once it is in a generally usable state for testers and users!

**Comment by tintou** [comment] 2018-11-07 16:34
Hold `⌘` and drag the window until this is fixed

**Comment by dreiggy** [comment] 2018-12-17 20:55
I have same issue :/
![screenshot from 2018-12-17 22-46-10](https://user-images.githubusercontent.com/7572869/50114980-c4903300-024e-11e9-84bc-83e60cb931b2.png)
