### ISSUE TITLE
mail not working with email account use protection 2-step verification

### ISSUE THREAD

**Issue by torikulhabib** [elementary/mail#191] opened 2018-02-17 11:48 UTC
i am sorry, i can't use mail because mail not supported 2-step verification.
i use verification username password and SMS otp verification.
please add this fitur.

**Comment by andbuitra** [comment] 2018-02-17 14:54
Hello.

This is issue has already been posted on #41 so please consider closing this one and head out there to keep the discussion alive and centralized.

As a workaround you may try what I commented a couple of minutes ago. Use Google's One Time Password so you can get into your Gmail account with 2FA enabled.

**Comment by danrabbit** [comment] 2018-10-22 22:41
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2018-10-22 22:41 UTC
