### ISSUE TITLE
Large email causes crash and exit

### ISSUE THREAD

**Issue by joedborg** [elementary/mail#414] opened 2019-08-19 18:21 UTC
Trying to view a large email, which is a cron dump.

```
(pantheon-mail:5072): Gdk-ERROR **: 14:19:11.427: The program 'pantheon-mail' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAlloc (insufficient resources for operation)'.
  (Details: serial 11482 error_code 11 request_code 53 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
[1]    5072 trace trap  pantheon-mail
```

**Comment by andbuitra** [comment] 2019-08-22 22:09
Possible duplicate of #407 

This is exactly what happens in my case (ref: https://github.com/elementary/mail/issues/407#issuecomment-516406223)

**Comment by andbuitra** [comment] 2019-08-22 22:09
@danrabbit

**Comment by ryonakano** [comment] 2019-08-22 22:11
Duplicate of #407

**Closed** 2019-08-22 22:11 UTC
