### ISSUE TITLE
Pantheon-Mail crashing when replying to mail

### ISSUE THREAD

**Issue by Silberling** [elementary/mail#177] opened 2017-11-16 03:46 UTC
Mail freezes for some time, after that, either I can continue writing (again with huge lags) or it crashes completely.

	[deb] 04:40:50 10,069200 imap-engine-minimal-folder.vala:641: Fetching STATUS for remote Gmail:HIDDENEMAILADDRESS@googlemail.com:[Google Mail]/Drafts (open_count=1 remote_opened=true) from local
	[deb] 04:40:50 0,007686 imap-engine-minimal-folder.vala:645: Fetching information for remote folder Gmail:HIDDENEMAILADDRESS@googlemail.com:[Google Mail]/Drafts (open_count=1 remote_opened=true)
	[deb] 04:40:50 0,000144 imap-engine-minimal-folder.vala:649: Opening remote folder [Google Mail]/Drafts
	[deb] 04:40:50 0,302856 imap-client-session.vala:1455: [0002/imap.gmail.com/default:993 GEARY_IMAP_CLIENT_SESSION_STATE_CONNECTING] Connected to imap.gmail.com/default:993
	[deb] 04:40:50 0,000010 imap-client-session.vala:624: [0002/imap.gmail.com/default:993 GEARY_IMAP_CLIENT_SESSION_STATE_CONNECTING] Connected
	[deb] 04:40:50 0,066768 imap-client-session.vala:1528: [0002/imap.gmail.com/default:993 GEARY_IMAP_CLIENT_SESSION_STATE_NOAUTH] capability #1: NAMESPACE IMAP4rev1 X-GM-EXT-1 XYZZY "AUTH=OAUTHBEARER" "AUTH=PLAIN" "AUTH=XOAUTH" "AUTH=PLAIN-CLIENTTOKEN" "AUTH=XOAUTH2" UNSELECT SASL-IR CHILDREN XLIST QUOTA ID IDLE
	[deb] 04:40:50 0,002397 imap-client-session.vala:718: [0002/imap.gmail.com/default:993 GEARY_IMAP_CLIENT_SESSION_STATE_NOAUTH] use_starttls=false is_ssl=true starttls=false
	[deb] 04:40:50 0,000029 imap-client-session.vala:746: [0002/imap.gmail.com/default:993 GEARY_IMAP_CLIENT_SESSION_STATE_NOAUTH] No STARTTLS attempted
	[deb] 04:40:51 0,808764 imap-client-session.vala:1528: [0002/imap.gmail.com/default:993 GEARY_IMAP_CLIENT_SESSION_STATE_AUTHORIZING] capability #2: NAMESPACE "UTF8=ACCEPT" IMAP4rev1 X-GM-EXT-1 ENABLE UNSELECT "COMPRESS=DEFLATE" UIDPLUS CONDSTORE CHILDREN MOVE LIST-EXTENDED SPECIAL-USE LITERAL- XLIST ESEARCH LIST-STATUS QUOTA ID IDLE "APPENDLIMIT=35651584"
	[deb] 04:41:21 29,822333 imap-client-connection.vala:784: [0002/74.125.206.108:993/GEARY_IMAP_CLIENT_CONNECTION_STATE_CONNECTED] on_cmd_timeout
	[deb] 04:41:21 0,000039 imap-client-session.vala:1610: [0002/imap.gmail.com/default:993 GEARY_IMAP_CLIENT_SESSION_STATE_AUTHORIZED] Receive failed: No response to command(s) after 30 seconds
	[deb] 04:41:21 0,000009 imap-client-session.vala:1323: [0002/imap.gmail.com/default:993 GEARY_IMAP_CLIENT_SESSION_STATE_AUTHORIZED] Receive error, disconnecting: No response to command(s) after 30 seconds
	[deb] 04:41:21 0,000052 imap-deserializer.vala:250: [des:0002/GEARY_IMAP_DESERIALIZER_STATE_TAG] Waiting for deserializer to close...

	(pantheon-mail:12146): Gdk-ERROR **: The program 'pantheon-mail' received an X Window System error.
	This probably reflects a bug in the program.
	The error was 'BadLength (poly request too large or internal Xlib length erro'.
	  (Details: serial 296542 error_code 16 request_code 18 (core protocol) minor_code 0)
	  (Note to programmers: normally, X errors are reported asynchronously;
	   that is, you will receive the error a while after causing it.
	   To debug your program, run it with the GDK_SYNCHRONIZE environment
	   variable to change this behavior. You can then get a meaningful
	   backtrace from your debugger if you break on the gdk_x_error() function.)
	Trace/breakpoint trap (core dumped)

This is a gmail mailbox with 3-5 GB of mails from the past 10 years, several labels.

syslog

	Nov 16 04:18:18 luna kernel: [141100.915294] traps: pantheon-mail[11592] trap int3 ip:7f269c473a5b sp:7fff9c00f5f0 error:0
	Nov 16 04:18:18 luna kernel: [141100.915304]  in libglib-2.0.so.0.4800.2[7f269c423000+10f000]
	Nov 16 04:19:32 luna kernel: [141174.857157] traps: pantheon-mail[12146] trap int3 ip:7f3cf8616a5b sp:7ffc7cc29340 error:0
	Nov 16 04:19:32 luna kernel: [141174.857167]  in libglib-2.0.so.0.4800.2[7f3cf85c6000+10f000]

This crash makes pantheon-mail unusable so I'd like to help to fix this issue. If there is any way to help, let me know how I can contribute. If there is any way to get more information that might help you just tell me.

pantheon-mail/xenial,now 1.0.6+r2349+pkg15+r1~ubuntu0.4.1.1 amd64

**Comment by andbuitra** [comment] 2018-02-17 14:51
Hello,

I'm having the same issue. My office mail is quite large and I also handle my personal and college email there. It starts to get really laggy and then crashes. This ended up on the "window resizing" bug after a couple of weeks with these issues.

OP, could you try to replicate this behavior on Geary? I know Mail is mostly just a fresh look of Geary with the Granite Toolkit. However none of the issues I mentioned are present in Geary so I think something changed on the transition or Mail is an outdated version of buggy Geary that has been fixed since then.

**Comment by Silberling** [comment] 2018-02-24 13:39
I'm sorry, I have no Linux machine running with a GUI at the moment. This was a test if Linux would work for me in a test over some months and switched back to Windows 4 Weeks ago.

**Comment by danrabbit** [comment] 2018-10-17 22:13
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2018-10-17 22:13 UTC
