### ISSUE TITLE
Window enlarges itself during some mouse events

### ISSUE THREAD

**Issue by aqiank** [elementary/mail#147] opened 2017-08-24 06:17 UTC
This is pantheon-mail v1.0.5 on ElementaryOS Loki.

Here's a video that shows what happens:
https://youtu.be/qgWHdudozi8

I can't resize it down either. It started happening since some time last week I think.

**Comment by btkostner** [comment] 2017-09-06 02:15
I'm going to close this as it seems to be a duplicate of #1.

**Closed by btkostner** 2017-09-06 02:15 UTC
