### ISSUE TITLE
Unable to validate - Gmail

### ISSUE THREAD

**Issue by aadilayub** [elementary/mail#220] opened 2018-06-11 10:53 UTC
I get a login error every time I try to add my Gmail account. I triple checked the username and password; they are correct and work perfectly fine on browsers and mobile devices. I even tried logging in with a different email account and ran into this bug again. 

The same issue shows up when adding my Gmail account to the calendar app.

![image](https://user-images.githubusercontent.com/31581044/41227708-59ee8bea-6da8-11e8-90b4-d071d4ef5781.png)

**Comment by ryonakano** [comment] 2018-06-11 12:07
![screenshot from 2018-06-11 20-55-46](https://user-images.githubusercontent.com/26003928/41230203-db11681c-6db9-11e8-8817-1b00e4db65c8.png)

This is because Mail and Calendar don't support OAuth 2.0 (see #41). I think you can add your Gmail account to the both apps by turning on the "Allow less secure apps" setting in Google's "My Account" page.

**Comment by ryonakano** [comment] 2018-06-12 11:15
@aadilayub So, this is duplication of #41 and is not a bug. Thus I think it is better for you to close this issue.

**Comment by aadilayub** [comment] 2018-06-13 08:12
Got it! Apologies. Still new to this open source thing. Thanks for the fix!

**Closed** 2018-06-13 08:12 UTC

**Comment by redplant0** [comment] 2019-07-08 17:25
I'm experiencing similar issue. I've already tried turning on the option to allow less secured apps from my Google account, and still the issue pops up whenever I try logging in on the app.

**Comment by andbuitra** [comment] 2019-07-13 01:36
@redplant0 Do you have 2FA enabled? If yes then generate an app password. You should be able to log in with that.
