### ISSUE TITLE
AppCenter listing says mail is multiplayer 

### ISSUE THREAD

**Issue by hanaral** [elementary/mail#713] opened 2021-10-05 13:25 UTC
### What Happened?

AppCenter listing for mail has the multiplayer infocard, when it is in actuality singleplayer only :(
![Screenshot from 2021-10-05 14-23-34](https://user-images.githubusercontent.com/58219504/136031598-830f58b1-d7d2-4cad-a3e1-93ca6f3c7fec.png)

### Steps to Reproduce

1. Open Mail in AppCenter

### Expected Behavior

singleplayer (no multiplayer card)

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by davidmhewitt** [comment] 2021-10-05 13:28
You mean you don't player multiplayer games like Chess via your mail client? It's entirely possible ;)

But really, this is a duplicate of:
https://github.com/elementary/appcenter/issues/1676

The AppData for Mail is fine, it's just the way that AppCenter presents this information.

Thanks for the report though!

**Closed by davidmhewitt** 2021-10-05 13:28 UTC
