### ISSUE TITLE
Mail crashes when it has to open a large ascii email

### ISSUE THREAD

**Issue by kdekooter** [elementary/mail#33] opened 2017-06-03 05:14 UTC
The size of the mail causing the problem is 877K. It is an all-ASCII logwatch report.
Quite annoying because there is no way to the delete them mail, the app has crashed before you get a chance.

This is the relevant log info:
```
Oct  9 08:04:10 la-palma gnome-session[1867]: (pantheon-mail:11804): Gtk-WARNING **: drawing failure for widget 'StylishWebView': invalid value (typically too big) for the size of the input (surface, pattern, etc.)
Oct  9 08:04:10 la-palma gnome-session[1867]: (pantheon-mail:11804): Gtk-WARNING **: drawing failure for widget 'GtkGrid': invalid value (typically too big) for the size of the input (surface, pattern, etc.)
Oct  9 08:04:10 la-palma gnome-session[1867]: (pantheon-mail:11804): Gtk-WARNING **: drawing failure for widget 'GtkGrid': invalid value (typically too big) for the size of the input (surface, pattern, etc.)
Oct  9 08:04:10 la-palma gnome-session[1867]: (pantheon-mail:11804): Gtk-WARNING **: drawing failure for widget 'GtkRevealer': invalid value (typically too big) for the size of the input (surface, pattern, etc.)
Oct  9 08:04:10 la-palma gnome-session[1867]: (pantheon-mail:11804): Gtk-WARNING **: drawing failure for widget 'GtkGrid': invalid value (typically too big) for the size of the input (surface, pattern, etc.)
Oct  9 08:04:10 la-palma gnome-session[1867]: (pantheon-mail:11804): Gtk-WARNING **: drawing failure for widget 'ConversationWidget': invalid value (typically too big) for the size of the input (surface, pattern, etc.)
Oct  9 08:04:10 la-palma gnome-session[1867]: (pantheon-mail:11804): Gtk-WARNING **: drawing failure for widget 'GtkListBox': invalid value (typically too big) for the size of the input (surface, pattern, etc.)
Oct  9 08:04:10 la-palma kernel: [ 5511.114985] traps: pantheon-mail[11804] trap int3 ip:7fce103a9a5b sp:7ffcb1c4cc20 error:0
Oct  9 08:04:10 la-palma gnome-session[1867]: (pantheon-mail:11804): Gdk-ERROR **: The program 'pantheon-mail' received an X Window System error.
Oct  9 08:04:10 la-palma gnome-session[1867]: This probably reflects a bug in the program.
Oct  9 08:04:10 la-palma gnome-session[1867]: The error was 'BadAlloc (insufficient resources for operation)'.
Oct  9 08:04:10 la-palma kernel: [ 5511.116439] ecryptfs_encrypt_page: Error attempting to write lower page; rc = [-4]
Oct  9 08:04:10 la-palma kernel: [ 5511.116452] ecryptfs_write_end: Error encrypting page (upper index [0x0000000000000006])
Oct  9 08:04:10 la-palma gnome-session[1867]:   (Details: serial 2538 error_code 11 request_code 53 (core protocol) minor_code 0)
Oct  9 08:04:10 la-palma gnome-session[1867]:   (Note to programmers: normally, X errors are reported asynchronously;
Oct  9 08:04:10 la-palma gnome-session[1867]:    that is, you will receive the error a while after causing it.
Oct  9 08:04:10 la-palma gnome-session[1867]:    To debug your program, run it with the GDK_SYNCHRONIZE environment
Oct  9 08:04:10 la-palma gnome-session[1867]:    variable to change this behavior. You can then get a meaningful
Oct  9 08:04:10 la-palma gnome-session[1867]:    backtrace from your debugger if you break on the gdk_x_error() function.)
```

**Comment by Pardaigle** [comment] 2018-03-25 13:21
This bug is very annoying and still present.

**Comment by kdekooter** [comment] 2018-05-12 12:04
Hmm. That was a one time treat. Now it is flat out crashing again.

**Comment by kdekooter** [comment] 2018-05-12 12:08
Any chance this bug will get some attention in the near future @danrabbit?

**Comment by mdh34** [comment] 2018-05-28 17:11
Closing as a duplicate of #27 - there have been a lot of reports for this bug, so i suggest we centralise  things there

**Closed by mdh34** 2018-05-28 17:11 UTC
