### ISSUE TITLE
mail does not access gmail when registering account

### ISSUE THREAD

**Issue by paulo8448** [elementary/mail#420] opened 2019-09-26 14:53 UTC
I try to register gmail in the mail but the application does not enter it shows that the password is wrong but I'm writing correctly

![Captura de tela de 2019-09-26 11-52-05](https://user-images.githubusercontent.com/33562708/65699281-3ace8b00-e054-11e9-89be-25a9f791e3f5.png)

**Comment by ryonakano** [comment] 2019-09-26 22:33
![screenshot from 2018-06-11 20-55-46](https://user-images.githubusercontent.com/26003928/41230203-db11681c-6db9-11e8-8817-1b00e4db65c8.png)

This is because Mail doesn't support OAuth 2.0 (please see #41). I think you can add your Gmail account by turning on the "Allow less secure apps" setting in Google's "My Account" page.

Closing as a duplicate of #41

**Closed by ryonakano** 2019-09-26 22:33 UTC
