### ISSUE TITLE
Change Rubbish Bin to Trash

### ISSUE THREAD

**Issue by D0J0P** [elementary/mail#291] opened 2018-10-22 22:28 UTC
It would be more consistent, like how Files does it. Also, I made sure the keyboard format wasn't in UK English, as I'm pretty sure we don't say "Rubbish Bin".

When you right-click it, the option says "Empty Trash" anyway.

**Comment by danrabbit** [comment] 2018-10-22 22:34
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2018-10-22 22:34 UTC
