### ISSUE TITLE
Shows E-Mails even though the PW was wrong!!!

### ISSUE THREAD

**Issue by risou-to-genjitsu** [elementary/mail#342] opened 2019-01-09 19:36 UTC
Hi there,
I thought to give your mail a try. Logged in with one of my e-mail-addresses all the time, but never set password to remember.
Today I needed to write an important Mail and wanted to Log-In the same way i do always. But I typed the password wrong. 
---> I didn't have access, but I was able to see my INBOX without the right password. This was very alarming to me instantly. So I write this to you to fix it ASAP.  

Linux itachi-K73SM **4.15.0-43-generic** #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux **elementary OS 5.0 Juno**  GTK+ 3.22.30

Please fix this. Thanks in Advance.

**Comment by danrabbit** [comment] 2019-01-09 22:51
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2019-01-09 22:51 UTC
