### ISSUE TITLE
Mail can't connect to Gmail service if 2FA is enabled

### ISSUE THREAD

**Issue by aidenlangley** [elementary/mail#457] opened 2020-02-18 03:41 UTC
Not much else to add except that I am receiving the username/password is incorrect due to the fact that I have 2FA enabled but a request is not being sent to my authentication device to approve the login.

**Comment by rasmus91** [comment] 2020-02-19 14:19
It is possible through something called '[app passwords](https://support.google.com/accounts/answer/185833)' though it's not super intuitive, it's alright to setup by reading the guide.

**Comment by danrabbit** [comment] 2020-02-19 16:59
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2020-02-19 16:59 UTC

**Comment by moevbiz** [comment] 2020-04-22 18:49
I am getting the same error. Is it possible that I am using an outdated version of Mail?
