### ISSUE TITLE
There is no new message notification for IMAP folders

### ISSUE THREAD

**Issue by WebShapedBiz** [elementary/mail#216] opened 2018-05-20 17:52 UTC

**Comment by danrabbit** [comment] 2018-10-22 22:40
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2018-10-22 22:40 UTC

**Comment by WebShapedBiz** [comment] 2018-10-23 03:34
Thank you @danrabbit for your time and effort.
