### ISSUE TITLE
E-mail reply sent with wrong "From" address

### ISSUE THREAD

**Issue by wolframroesler** [elementary/mail#480] opened 2020-05-12 11:01 UTC
## Prerequisites

- [x] I have searched open and closed issues for duplicates.

## Describe the bug

Replying to a mail and editing it in the "drafts" folder replaces the sender of the reply (which should be me) by the sender of the original mail. For example, if John sends me a mail, and I reply to John's mail, but before sending the reply I store it as a draft and edit and send it later, John will receive a mail that pretends to be sent by John instead of by me.

Yes, really. To the recipient it looks as if I tried to send a mail under his name. Elementary Mail is spoofing the sender address!

### To Reproduce

1. Go to Inbox and click an e-mail.
1. Click "Reply".
1. Write something, then press ^S to save the mail as a draft.
1. Go the the "Drafts" folder.
1. Click on the mail you saved in the previous step.
1. Click the pencil icon to edit the mail.
1. Write something, then press ^S to save the draft.
1. Close the editor window.
1. Check the "From" field of the draft.

The "From" name and address should be my own, but it's the name and address of the sender of the mail I'm replying to.

### Expected behavior

The "From" name and address of the new mail should be mine.

### Screenshots or screen recordings

This is the mail I received and to which I want to reply.

![1](https://user-images.githubusercontent.com/25565229/81676042-c532f600-944f-11ea-9327-571ecb10cd44.png)

After clicking "Reply", edit it and save it as a draft.

![2](https://user-images.githubusercontent.com/25565229/81676046-c5cb8c80-944f-11ea-8c75-4de58b53d7a4.png)

This is the draft in the "Drafts" folder. Note that the "From" name and address are my own, as it should be.

![3](https://user-images.githubusercontent.com/25565229/81676048-c6642300-944f-11ea-90ce-6a400a66ab40.png)

Now edit the draft.

![4](https://user-images.githubusercontent.com/25565229/81676052-c6fcb980-944f-11ea-8a9c-149fd57db4f7.png)

After editing and saving the draft, the "From" name and address have changed.

![5](https://user-images.githubusercontent.com/25565229/81676054-c6fcb980-944f-11ea-9c60-3fe145f20b4d.png)

### Logs

None.

## Platform Information

![about](https://user-images.githubusercontent.com/25565229/81675147-a08a4e80-944e-11ea-8084-99aeb1feff21.png)

## Additional context

This is a serious bug that significantly compromises the trust I have in this software. I recommend using a different e-mail client until this bug is fixed.

**Comment by wolframroesler** [comment] 2020-05-30 18:30
Hello, is anyone listening? Can anyone reproduce the bug? Does anyone agree that this is a very serious issue?

**Comment by androthan** [comment] 2020-05-31 19:44
Hi. I tried twice to reproduce your described bug step by step. **I wasn't able to reproduce the issue.** (elementary OS 5.1.4, Mail 1.0.8, imap)

**Comment by danrabbit** [comment] 2020-05-31 21:16
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

For future issue reports, please be aware that we typically work a regular 5-day work week schedule in US time zones. It is not typical to get a response within a few hours on weekend. There is no 24/7 on call staff available to triage issue reports.

**Closed by danrabbit** 2020-05-31 21:16 UTC
