### ISSUE TITLE
Mail does not remembering position, window size and size of window elements

### ISSUE THREAD

**Issue by ghabit** [elementary/mail#452] opened 2020-01-18 14:11 UTC
Mail does not remembering position, window size and size of window elements.
That hiding names of accounts, and forces to resize window and window elements each start.

**Comment by ryonakano** [comment] 2020-01-18 22:08
Does your issue look like this? https://github.com/elementary/mail/issues/222#issue-337367579

**Comment by ghabit** [comment] 2020-01-20 04:24
My window change size each start, and become sort of bigger every time. Also width of the columns (accounts, list of emails, email view window) is changing every start too.

**Comment by ryonakano** [comment] 2020-01-20 07:56
@ghabit OK, could you attach a screencast animation gif that shows your issue with screencast app like [Screen Recorder](https://appcenter.elementary.io/com.github.mohelm97.screenrecorder)?

**Comment by ghabit** [comment] 2020-01-20 16:24
It is a bit different behaviour time after time, here is screencast of today issue.
I have adjusted size of collums UI, window size and position. 
Then closed and opened applications serveral times (got crashes during the process)
At final attempt left column, containing account names - is stretched and unreadable - too slim.
![Запись экрана от 2020-01-20 19 16 34](https://user-images.githubusercontent.com/70936/72742085-1164dc80-3bba-11ea-8621-84253304b379.gif)

**Comment by ryonakano** [comment] 2020-01-20 21:27
Thank you for your screencast. Judging from it and your comments, I guess this issue might be a duplicate of #411 and #324.

**Comment by ghabit** [comment] 2020-01-21 04:18
Looks like we can close this issue in that case. Haven’t voted maximizing window bug because of columns resizing.

**Closed** 2020-01-21 10:51 UTC
