### ISSUE TITLE
Gmail with two-factor auth = fail

### ISSUE THREAD

**Issue by mrsergvit** [elementary/mail#182] opened 2018-01-13 11:35 UTC
The app looks nice, but I can't login to mine gmail account.
It shows me a message about wrong entry data, but data is ok.
One different - enabled two-factor authorization.

**Comment by tintou** [comment] 2018-01-14 11:39
Duplicate of #41

**Closed by tintou** 2018-01-14 11:39 UTC

**Comment by gudge25** [comment] 2019-11-11 08:08
Still cant login Gmail with two-factor auth

**Comment by ryonakano** [comment] 2019-11-11 09:15
@gudge25 See https://github.com/elementary/mail/issues/41#issuecomment-407006652
