### ISSUE TITLE
When you click on mail's content it scrolls back to the top

### ISSUE THREAD

**Issue by timkrief** [elementary/mail#114] opened 2017-07-24 19:24 UTC
When I try to click on a link after scrolling down with my mouse wheel, It scrolls back to the top and I have to go back to that link to click again.

**Comment by davidmhewitt** [comment] 2017-07-24 19:26
Thank you for the report.

This is a duplicate of #6 which has now been fixed. The next update of mail should contain this fix.

**Closed by davidmhewitt** 2017-07-24 19:26 UTC

**Comment by timkrief** [comment] 2017-07-24 19:31
Cool ! Thanks a lot !
