### ISSUE TITLE
How to solve "Error saving sent mail"

### ISSUE THREAD

**Issue by pefferen** [elementary/mail#149] opened 2017-09-08 12:26 UTC
Multiple things happen, they might be related. I have 2 imap accounts setup in Mail. I try sending a mail from one to the other. The message gets send, that good. But the send messages stay in the 'outgoing mail' folder aswell. And an error message is displayed in the folder bar lower left corner saying "Error saving sent mail".

When I try to run mail in debug mode, I do not get any debug messages, insted mail is detached and run instead. using the following command:

`$ pantheon-mail --debug`

Any ideas on how to resolve this issue?

**Comment by matzipan** [comment] 2017-09-08 12:30
Before running with `--debug` you need to do a `killall -9 pantheon-mail` to kill the existing background processes.

**Comment by pefferen** [comment] 2017-09-08 12:56
tnx @matzipan that did it. Aparently with my setup, Mail tried to create the special folders in my Imap account, but the server denied that.

As workaround I setup the folders manually by editing the `geary.ini` file found in `~/.local/share/geary/<mailbox name>`.

Now as a result I got all the special folders, and after sending an email the message is moved from the outgoing mail folder to the 'sent mail' folder.

Still I more useful error message could be displayed, and a settings from to set the mail folders for this use case.

**Comment by danirabbit** [comment] 2023-04-14 18:39
Thanks for your report! We've done a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danirabbit** 2023-04-14 18:39 UTC
