### ISSUE TITLE
Mail application does not work

### ISSUE THREAD

**Issue by sgb84** [elementary/mail#521] opened 2020-11-24 00:07 UTC
I cannot connect gmail to this email client. The message repeats regularly:
"Failed to confirm:
Invalid IMAP username or password.
Invalid SMTP username or password. "
I am sure that my email address and password are correct. Help fix this please.
![Снимок экрана от 2020-11-24 01 56 04](https://user-images.githubusercontent.com/74938189/100029250-88ca5480-2df9-11eb-9282-a549e4270088.jpeg)

**Comment by SashaBrankovic** [comment] 2021-01-05 10:17
Invalid username or password on Google. NOT WORKS!

**Comment by danrabbit** [comment] 2021-01-05 19:32
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2021-01-05 19:32 UTC
