### ISSUE TITLE
Mail app Bugs

### ISSUE THREAD

**Issue by test-user0** [elementary/mail#454] opened 2020-02-04 01:35 UTC
Hello Elementary Team. I would to report some problems I'm having with the Mail app. 

I cannot add more than one account and I can't delete an account. So I decided to remove the folder in the patheon-mail folder; I launched the app it did not work. 
So I decided to uninstall and install the app and for some reason every time I boot the computer the Mail app opens by itself. 

Thanks for your patience.

**Comment by danrabbit** [comment] 2020-12-21 22:22
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2020-12-21 22:22 UTC
