### ISSUE TITLE
Does not support NTLM authentication to STMP servers

### ISSUE THREAD

**Issue by flyingdutchman** [elementary/mail#351] opened 2019-02-11 20:40 UTC
Hi !

I'm trying to add my school's email to the elementary mail app and with the correct IMAP and SMTP settings I get a "smtp username or password incorrect password" error.

I tried to connect to my account using Thunderbird and it works with the same IMAP and SMTP parameters. The only difference being that in Thunderbird it uses NTLM to connect to the SMTP server.

I suppose that the mail app is trying to connect to the server with a classic authentication and fails.

![image](https://user-images.githubusercontent.com/26379223/52591884-51b5c980-2e45-11e9-9a68-72b874d6e9aa.png)

(The "already added to Mail" error is because I did a workaround to at least see the mails by disabling SMTP authentication, but the error is still the same)

**Comment by danrabbit** [comment] 2019-02-11 21:37
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2019-02-11 21:37 UTC

**Comment by flyingdutchman** [comment] 2019-02-11 21:51
Could we have a idea of when the new version will be out ? (Day/Week/Month ?)
