### ISSUE TITLE
ot showing new messages in the message list.

### ISSUE THREAD

**Issue by timurberetar** [elementary/mail#142] opened 2017-08-13 14:27 UTC
When you receive a message notification that a message has come. But you don't see it. Only helps restart the client.

**Comment by danrabbit** [comment] 2021-09-23 18:40
I'm unable to confirm this issue report with the latest version of Mail. Since this is a pretty old report, I'm going to go ahead and close it and assume it was fixed! If you're able to reproduce this issue with the latest version of mail, feel free to reopen :)

**Closed by danrabbit** 2021-09-23 18:40 UTC
