### ISSUE TITLE
Setup window does nothing

### ISSUE THREAD

**Issue by drom98** [elementary/mail#383] opened 2019-06-06 15:54 UTC
I'm trying to add an office365 email from my university, but when I press the button add, the window got blank and does nothing.

![](https://i.imgur.com/34d04fg.gif)

**Comment by danrabbit** [comment] 2019-06-06 17:07
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2019-06-06 17:07 UTC
