### ISSUE TITLE
Today I broke the mail app

### ISSUE THREAD

**Issue by WattanaGaming** [elementary/mail#241] opened 2018-09-26 05:27 UTC
![screenshot from 2018-09-26 11-55-52](https://user-images.githubusercontent.com/25323231/46058961-655adf00-c187-11e8-8623-863382775316.png)
Any idea what cause this?

**Comment by danrabbit** [comment] 2018-09-26 19:03
Closing as a duplicate of #1

**Closed by danrabbit** 2018-09-26 19:03 UTC

**Comment by WattanaGaming** [comment] 2018-09-27 02:38
For bug sake its not the same problem. it happens then i resize the width of inbox list too far, not when launching
