### ISSUE TITLE
Email is sent twice

### ISSUE THREAD

**Issue by younesbenmoussa** [elementary/mail#331] opened 2018-12-06 17:45 UTC
Hi,

When i send an email or reply, the email is sent twice.

To produce this behavior : send a new or reply to an email  then check your "sent mail" folder.

**Comment by danrabbit** [comment] 2018-12-06 17:49
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2018-12-06 17:49 UTC
