### ISSUE TITLE
Cannot move e-mails after suspend

### ISSUE THREAD

**Issue by boetk** [elementary/mail#321] opened 2018-11-06 20:12 UTC
Having mail open or minimized while suspending elementary OS, the Mail application cannot move files by drag and drop afterwards.
Expected was that the e-mail is moved, but instead the e-mail is still in the original folder still being marked.

Mail needs a restart to move e-mails again.

**Comment by danrabbit** [comment] 2020-12-21 22:17
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2020-12-21 22:17 UTC
