### ISSUE TITLE
REGRESSION: Mail still forgetting password

### ISSUE THREAD

**Issue by stobbsm** [elementary/mail#421] opened 2019-09-29 16:13 UTC
## Prerequisites
- [X] I have searched open and closed issues for duplicates.

## Describe the bug
When using Panteon-mail with my own email server, I keep getting prompted for my password, even though I select "save passwords". The box is always checked, and the entry exists in my keyring (verified with seahorse).

If applicable, add screenshots or screen recordings to help explain your problem.

### To Reproduce
1. Open Pantheon-mail
2. Add a new imap account
3. Spend a minute or so viewing email
4. Password prompt appears every minute or so.

### Expected behavior
Password is saved and used from the keyring.

### Screenshots or screen recordings
Will provide when I'm at my laptop again.

### Logs
I'm unable to find any logs. Please advise.

## Platform Information
Elementary OS Juno, latest updates, Dell XPS 13 9350

- [ ] I'm using the latest version from git that I've manually compiled
- [X] I'm using the latest released stable version

## Additional context
Have not testing with Gmail, and Online Accounts does not place the Imap account into mail for access yet.

**Comment by danrabbit** [comment] 2020-12-21 22:20
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2020-12-21 22:20 UTC
