### ISSUE TITLE
Change password request dialog to action toast

### ISSUE THREAD

**Issue by btkostner** [elementary/mail#145] opened 2017-08-18 16:31 UTC
_I'm not sure if this will be relevent with the new rewrite, but..._

## Actual
Currently if mail gets an authentication error from the server a dialog pops up asking for a new password.

## Expected
If an authentication error occures, an action toast with a button to account settings should appear. This avoids spamming the user with dialogs if something bad happens, and provides a nicer user experience.

**Comment by danrabbit** [comment] 2018-10-22 22:43
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2018-10-22 22:43 UTC
