### ISSUE TITLE
Recieved mail dialog's "OK" and "Cancel" buttons do not communicate well what they do.

### ISSUE THREAD

**Issue by quequotion** [elementary/mail#42] opened 2017-06-22 12:21 UTC
The alert dialog's buttons do not express that "OK" opens the message in mail immediately, and "Cancel" clears the dialog without opening the message.

Sorry to make more work for the translators, but these buttons should say something like "Read now" and "Read later".

**Comment by cassidyjames** [comment] 2017-06-22 13:51
Could you clarify what dialog this is and when it shows?

**Comment by quequotion** [comment] 2017-06-23 03:18
The alert dialog, as specified in src/client/dialogs/alert-dialog.vala, lines 7-51: class AlertDialog

This is the dialog that appears when a message arrives in an inbox.

**Comment by danrabbit** [comment] 2018-10-17 16:03
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2018-10-17 16:03 UTC
