### ISSUE TITLE
Weird window size bug

### ISSUE THREAD

**Issue by kingogames** [elementary/mail#162] opened 2017-10-31 23:42 UTC
When I opened up Geary today, the window spans wider than the screen and is super narrow. I can't resize the window or maximize, I can only close it.
![screenshot from 2017-10-30 16 09 00](https://user-images.githubusercontent.com/13295856/32253847-ca538462-be62-11e7-8309-ce78d9748ff3.png)

**Comment by josephholsten** [comment] 2017-11-09 22:12
@kingogames did you figure out how to get out of the situation? and then perhaps how to reproduce it?

**Comment by btkostner** [comment] 2017-11-09 22:13
Could this be related to: https://github.com/elementary/mail/issues/1?

**Comment by AlonsoEnrique** [comment] 2017-11-30 15:53
Same here: 
![crazymail](https://user-images.githubusercontent.com/1877511/33439942-b8c34356-d5bc-11e7-93ce-4d5a464e795a.gif)

**Comment by danrabbit** [comment] 2017-12-01 18:08
Closing as a duplicate of #1

**Closed by danrabbit** 2017-12-01 18:08 UTC
