### ISSUE TITLE
Clear message pane on delete

### ISSUE THREAD

**Issue by ryonakano** [elementary/mail#538] opened 2021-01-05 01:10 UTC
## What Happened

https://user-images.githubusercontent.com/26003928/103595346-8b62b280-4f3e-11eb-8d9f-6e59d5712a80.mp4

The selected message does not cleared in the message pane after deleting it.

## Expected Behavior

The message pane should be cleared after deleting currently selected message.

## Steps to Reproduce

1. Select some message. Its content is shown in the message pane in the right of the window
2. Delete the message
3. A toast tells you the selected message is deleted. However, the content of the message is still shown in the right pane

## Platform Information

- elementary OS Early Access with fully updated
- The latest master of Mail

**Comment by danrabbit** [comment] 2021-01-05 19:33
Closing as a duplicate of https://github.com/elementary/mail/issues/368

**Closed by danrabbit** 2021-01-05 19:33 UTC
Labels: Priority: Low
