### ISSUE TITLE
Mail sent out the same message 7 times

### ISSUE THREAD

**Issue by jmc-88** [elementary/mail#283] opened 2018-10-18 20:08 UTC
I've tried using Pantheon Mail on a Gmail account, connecting through IMAP/SMTP.
While this did work, I replied to a mail thread and somehow this resulted in SEVEN copies of the same message being sent out. If I open up Pantheon Mail now, it still reports 5 copies in the Drafts folder.

This looks sever enough to report, but I haven't yet managed to reproduce the issue or capture logs/other debugging info. I'll update this bug if I happen to find any.

### System

Fresh install of elementary OS Juno.

```
$ pantheon-mail --version
pantheon-mail 1.0.8
```

**Comment by danrabbit** [comment] 2018-10-18 20:15
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2018-10-18 20:15 UTC
