### ISSUE TITLE
Mail cannot log into gmail account

### ISSUE THREAD

**Issue by Isaac2k1** [elementary/mail#487] opened 2020-06-10 18:13 UTC
I've tested the PW several times in gmail in a browser and it worked well, but not at all in the Mail app.

error msg is: Unable to Validate: username or password incorrect.

Username contains ä (a-umlaut). email address does not contain ä.

**Comment by salperinlea** [comment] 2020-06-17 15:21
Having the same trouble as you, except username and adress just contain normal characters, and across all the gmail accounts I keep.

**Comment by ryonakano** [comment] 2020-06-17 20:59
![screenshot from 2018-06-11 20-55-46](https://user-images.githubusercontent.com/26003928/41230203-db11681c-6db9-11e8-8817-1b00e4db65c8.png)

This would be because Mail doesn't support OAuth 2.0 (see #41). I think you can add your Gmail account by turning on the "Allow less secure apps" setting in Google's "My Account" page.

Closing as a duplicate of #41

**Closed by ryonakano** 2020-06-17 20:59 UTC
