### ISSUE TITLE
Mail app responisveness

### ISSUE THREAD

**Issue by iamdenver** [elementary/mail#435] opened 2019-12-05 16:48 UTC
Hi! One issue I got so far with mail app is that I can't have full control resizing its sections.

Well, the video describes it better:)

[Screen record from.zip](https://github.com/elementary/mail/files/3928068/Screen.record.from.zip)

**Comment by danrabbit** [comment] 2019-12-05 19:41
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2019-12-05 19:41 UTC

**Comment by iamdenver** [comment] 2019-12-05 20:12
Soo, is it or gonna be okay?) 

Thank you as well for such a great experience!



Sent from myMail for iOS


Thursday, December 5, 2019, 9:41 PM +0200 from notifications@github.com  <notifications@github.com>:
