### ISSUE TITLE
Don't show authentication dialog on mail app after already adding an account from Online Accounts settings

### ISSUE THREAD

**Issue by uncertainquark** [elementary/mail#22] opened 2017-05-19 15:01 UTC
Opening the Mail app after adding an email account from Switchboard Settings > Online Accounts still shows the authentication dialog. The app still works even if the said dialog is ignored and closed.

![screenshot from 2017-05-19 16 24 36](https://cloud.githubusercontent.com/assets/22585732/26253764/f68586f2-3ca3-11e7-8581-390f9d492af9.png)

**Comment by danrabbit** [comment] 2018-10-17 16:04
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2018-10-17 16:04 UTC
Labels: Rewrite
