### ISSUE TITLE
app crash

### ISSUE THREAD

**Issue by tdapple** [elementary/mail#417] opened 2019-09-06 21:25 UTC
One specific mail (a newsletter from my kids school) causes pantheon-mail to crash and completely shutdown.. I ran it from the terminal so I could see any errors.. this is what I got. 

```
tdapple@format-c:~/Videos$ pantheon-mail 

(pantheon-mail:4171): Gtk-WARNING **: 16:21:27.784: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.

(pantheon-mail:4171): Gdk-ERROR **: 16:21:31.523: The program 'pantheon-mail' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAlloc (insufficient resources for operation)'.
  (Details: serial 25739 error_code 11 request_code 53 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
Trace/breakpoint trap
tdapple@format-c:~/Videos$ 
```

**Comment by tdapple** [comment] 2019-09-06 21:29
I don't know if it would help for me to forward the email ...I don't mind doing it since it's nothing personal.

**Comment by ryonakano** [comment] 2019-09-06 23:32
This sounds a duplicate of #407

**Comment by ryonakano** [comment] 2019-12-28 10:53
Probably a duplicate of #27

**Closed by ryonakano** 2019-12-28 10:53 UTC
