### ISSUE TITLE
Broken emojis in tag name

### ISSUE THREAD

**Issue by xchan14** [elementary/mail#644] opened 2021-08-14 09:25 UTC
## What Happened
In eOS 6, Most emojis are broken in the tag name of my email. 

## Expected Behavior
In eOS 5.1, I use emojis as icon for the tags of my email and they are displaying perfectly.

## Steps to Reproduce
1. Add emoji  tag name in your email on web browser.
2. Sync email account in Mail.
3. Validate emojis in tag names.

## Platform Information
Mail 6.1.0
elementary OS 6 Odin
Built on Ubuntu 20.04.2 LTS
Linux 5.11.0-25-generic

## Screenshot
In Mail app
![Screenshot from 2021-08-14 17-13-01](https://user-images.githubusercontent.com/26490513/129441365-1e58ef7e-2672-4255-9da1-69a1b8896e46.png)

In Email account
![Screenshot from 2021-08-14 17-23-14](https://user-images.githubusercontent.com/26490513/129441398-65d97e5a-7e29-42c3-ab0c-bc5e6c082959.png)

**Comment by marbetschar** [comment] 2021-08-16 10:18
Closing as duplicate of https://github.com/elementary/mail/issues/565

**Closed by marbetschar** 2021-08-16 10:18 UTC
