### ISSUE TITLE
Add Account Dialog (on first use) Goes Blank After Entering Details

### ISSUE THREAD

**Issue by seanballais** [elementary/mail#243] opened 2018-09-28 12:15 UTC
I was trying to add a new email account in Mail. I entered the details but pressing "Add" gives me a blank window and disabled buttons.

![Adding a new email account](https://user-images.githubusercontent.com/7175885/46207694-d6062500-c35a-11e8-9d57-79fcc1b37475.png)
**During credentials entry**

![screenshot from 2018-09-28 20 09 06](https://user-images.githubusercontent.com/7175885/46207695-d69ebb80-c35a-11e8-99fc-fc6c41cac738.png)
**After pressing the Add button**

What are the possible causes for that to happen?

**Comment by danrabbit** [comment] 2018-10-17 15:54
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2018-10-17 15:54 UTC
