### ISSUE TITLE
Pantheon Mail unresponsive

### ISSUE THREAD

**Issue by ghost** [elementary/mail#207] opened 2018-04-19 14:04 UTC
I have never had trouble with Pantheon mail until today.  This morning, the app center showed there were operating system updates, so I ran them.  Afterwards, I opened my email and after the program opened, the email program was unresponsive.  I tried rebooting the system, but I had the same result after reboot.  I also tried deleting the mail program and then reinstalling, but this didn't fix the issue either.

**Comment by danrabbit** [comment] 2018-10-17 15:57
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2018-10-17 15:57 UTC
