### ISSUE TITLE
Gmail treats Mail as a non secure app

### ISSUE THREAD

**Issue by raibtoffoletto** [elementary/mail#379] opened 2019-05-31 06:18 UTC
When adding a Gmail account, on should enable access from "less secure apps" in Google Account Settings to be able to successfully add the account. 

I haven't find any info regarding what makes an app get the status of "less secure app",
but we should look into the matter.

https://support.google.com/accounts/answer/6010255?hl=en-GB

**Comment by andbuitra** [comment] 2019-06-04 23:24
That status is for applications that don't have OAuth capabilities afaik. Enabling access for "less secure apps" doesn't work if you have two factor authentication. In that case you should use an "App Password" which generates an unique password that you cannot retrieve.

This has been reported before (#47 #191 )  which is why it surprises me that @danrabbit didn't close it. Maybe they are working on the integration?

**Comment by danrabbit** [comment] 2019-06-04 23:32
Yes this is a duplicate of #41 which has been closed since Mail now uses EDS as its backend. You can sign in to EDS uses GNOME's Google oauth integration for now. We're still trying to get approval from Google for our oauth integration in online accounts. Either way, this issue is no longer in the scope of Mail since it doesn't handle its own login anymore.

**Closed by danrabbit** 2019-06-04 23:32 UTC

**Comment by raibtoffoletto** [comment] 2019-06-11 04:48
Sorry for the duplicate! Since I didn't see any opened ticket regarding the issue, I opened a new one... however, independently of what back-end Mail is using now, this is still an issue to the end user and can drive new users away. If authorisation for gmail should be made in the Online-Accounts maybe it shouldn't appear in the add account on Mail ? Or a message redirecting the user to switchboard?

**Comment by tintou** [comment] 2019-06-11 05:08
There won't be any interface for this in the new Mail application ;) everything will be in the Online-Accounts
