### ISSUE TITLE
Mail badge sometimes displays wrong number

### ISSUE THREAD

**Issue by jtrees** [elementary/mail#175] opened 2017-11-15 08:52 UTC
#### Steps to Reproduce
1. Add two accounts to Mail
2. Receive one email per account

#### Expected Result
The Mail badge displays a "2".

#### Actual Result
The Mail badge displays a "1".

**Comment by danrabbit** [comment] 2018-10-22 22:40
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2018-10-22 22:40 UTC
