### ISSUE TITLE
No option to save inline images

### ISSUE THREAD

**Issue by kdwk** [elementary/mail#615] opened 2021-07-18 01:58 UTC
## What Happened

There is no option to save inline images as a file.

## Expected Behavior

There should be a 'Save image' option in the right-click context menu for inline images

## Steps to Reproduce

1. Receive an image embedded inline
2. Try to save it as a file

## Platform Information

![Screenshot from 2021-07-14 10-55-34](https://user-images.githubusercontent.com/39268094/126053332-30479efc-090f-4cab-bd0e-5a2aab3166ad.png)

**Comment by marbetschar** [comment] 2021-07-19 11:06
Closing this as a duplicate of #447

**Closed by marbetschar** 2021-07-19 11:06 UTC
