### ISSUE TITLE
Gmail - Less secure app

### ISSUE THREAD

**Issue by jordanbancino** [elementary/mail#47] opened 2017-07-03 21:41 UTC
Google does not allow Gmail users to use Mail because it is "an app that may put your account at risk". 

The mail app stops at this screen:
![screenshot from 2017-07-03 17 29 22](https://user-images.githubusercontent.com/27834353/27808366-68dfe460-6015-11e7-9beb-161577581872.png)

And shortly after, I will get this email: 

![screenshot from 2017-07-03 17 32 38](https://user-images.githubusercontent.com/27834353/27808455-ecff08ca-6015-11e7-89b7-598a1ee8a1f2.png)

This is a common issue among many mail clients I have tried, and I don't know for sure if it is a real security concern, but I would like to use Mail with my Gmail account.

I know that I can enable a feature on my account settings page that allows me to sign in with less secure apps, but I would really prefer not to do this.

**Comment by danrabbit** [comment] 2017-07-03 21:44
Closing as a duplicate of #41

**Closed by danrabbit** 2017-07-03 21:44 UTC
