### ISSUE TITLE
Email list width doesn't remember last set position

### ISSUE THREAD

**Issue by uncertainquark** [elementary/mail#209] opened 2018-05-03 07:11 UTC
The width of the email list randomly resets on new app launches. Try to adjust the width and relaunch the app multiple times to reproduce. 
![screenshot from 2018-05-03 12 36 54](https://user-images.githubusercontent.com/22585732/39563830-5656b022-4ecf-11e8-8857-5ea5513645aa.png)

**Comment by danrabbit** [comment] 2018-10-17 15:56
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2018-10-17 15:56 UTC
