### ISSUE TITLE
 Custom Font Selection for Displaying Email

### ISSUE THREAD

**Issue by gudge25** [elementary/mail#433] opened 2019-11-11 08:01 UTC
## Prerequisites
- [ ] I have searched open and closed issues for duplicates.

## Feature
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Existing work**

**Describe alternatives you've considered**

**Additional context**

**Comment by ryonakano** [comment] 2019-11-11 09:11
Closing as a duplicate of #431

**Closed by ryonakano** 2019-11-11 09:11 UTC
