### ISSUE TITLE
Mail crashes when opening some emails.

### ISSUE THREAD

**Issue by taehyounpark** [elementary/mail#110] opened 2017-07-23 00:41 UTC
Mail seems to crash when reading some emails. This one is from an Uber receipt email:
```
(pantheon-mail:9864): Gtk-WARNING **: drawing failure for widget 'StylishWebView': invalid value (typically too big) for the size of the input (surface, pattern, etc.)

(pantheon-mail:9864): Gtk-WARNING **: drawing failure for widget 'GtkGrid': invalid value (typically too big) for the size of the input (surface, pattern, etc.)

(pantheon-mail:9864): Gtk-WARNING **: drawing failure for widget 'GtkGrid': invalid value (typically too big) for the size of the input (surface, pattern, etc.)

(pantheon-mail:9864): Gtk-WARNING **: drawing failure for widget 'GtkRevealer': invalid value (typically too big) for the size of the input (surface, pattern, etc.)

(pantheon-mail:9864): Gtk-WARNING **: drawing failure for widget 'GtkGrid': invalid value (typically too big) for the size of the input (surface, pattern, etc.)

(pantheon-mail:9864): Gtk-WARNING **: drawing failure for widget 'ConversationWidget': invalid value (typically too big) for the size of the input (surface, pattern, etc.)

(pantheon-mail:9864): Gtk-WARNING **: drawing failure for widget 'GtkListBox': invalid value (typically too big) for the size of the input (surface, pattern, etc.)

(pantheon-mail:9864): Gdk-ERROR **: The program 'pantheon-mail' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAlloc (insufficient resources for operation)'.
  (Details: serial 72122 error_code 11 request_code 53 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
Trace/breakpoint trap (core dumped)
```

**Comment by giovannicaligaris** [comment] 2017-08-10 16:07
I am having a similar issue.

pantheon-mail 

(pantheon-mail:26102): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2045:14: 'min-height' is not a valid property name

(pantheon-mail:26102): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2046:13: 'min-width' is not a valid property name

(pantheon-mail:26102): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2051:13: 'min-width' is not a valid property name
No bp log location saved, using default.
[000:000] Cpu: 6.42.7, x4, 2301Mhz, 5878MB
[000:000] Computer model: Not available
No bp log location saved, using default.
[000:000] Cpu: 6.42.7, x4, 2301Mhz, 5878MB
[000:000] Computer model: Not available
[000:000] Browser XEmbed support present: 1
[000:000] Browser toolkit is Gtk2.
[000:000] Using Gtk2 toolkit
[000:012] Warning(optionsfile.cc:30): Load: Could not open file, err=2
[000:012] No bp log location saved, using default.
[000:012] Cpu: 6.42.7, x4, 2301Mhz, 5878MB
[000:013] Computer model: Not available
[000:005] Warning(optionsfile.cc:30): Load: Could not open file, err=2
[000:005] No bp log location saved, using default.
[000:005] Cpu: 6.42.7, x4, 2301Mhz, 5878MB
[000:005] Computer model: Not available
[000:005] Browser XEmbed support present: 1
[000:005] Browser toolkit is Gtk2.
[000:005] Using Gtk2 toolkit

(pantheon-mail:26102): Gtk-WARNING **: drawing failure for widget 'StylishWebView': invalid value (typically too big) for the size of the input (surface, pattern, etc.)

(pantheon-mail:26102): Gtk-WARNING **: drawing failure for widget 'GtkGrid': invalid value (typically too big) for the size of the input (surface, pattern, etc.)

(pantheon-mail:26102): Gtk-WARNING **: drawing failure for widget 'GtkGrid': invalid value (typically too big) for the size of the input (surface, pattern, etc.)

(pantheon-mail:26102): Gtk-WARNING **: drawing failure for widget 'GtkRevealer': invalid value (typically too big) for the size of the input (surface, pattern, etc.)

(pantheon-mail:26102): Gtk-WARNING **: drawing failure for widget 'GtkGrid': invalid value (typically too big) for the size of the input (surface, pattern, etc.)

(pantheon-mail:26102): Gtk-WARNING **: drawing failure for widget 'ConversationWidget': invalid value (typically too big) for the size of the input (surface, pattern, etc.)

(pantheon-mail:26102): Gtk-WARNING **: drawing failure for widget 'GtkListBox': invalid value (typically too big) for the size of the input (surface, pattern, etc.)

(pantheon-mail:26102): Gdk-ERROR **: The program 'pantheon-mail' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAlloc (insufficient resources for operation)'.
  (Details: serial 8445 error_code 11 request_code 53 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
Trace/breakpoint trap

**Comment by bksubhuti** [comment] 2017-09-29 14:23
I think it crashes when there is complex html.  My father sent me a news article and it crashed.  I can send it somewhere if you wish.

**Comment by kdekooter** [comment] 2017-10-09 07:13
This is a duplicate of #33

**Comment by mdh34** [comment] 2018-05-28 17:10
Closing as a duplicate of #27

**Closed by mdh34** 2018-05-28 17:10 UTC
Labels: Rewrite
