### ISSUE TITLE
Sign in for gmail does not work

### ISSUE THREAD

**Issue by sean89butler** [elementary/mail#315] opened 2018-10-30 13:07 UTC
When I open the Mail app and try to enter my credentials for Gmail, it always comes back with wrong user name or password. I know for a fact that all of my account info is correct.

**Comment by danrabbit** [comment] 2018-10-30 17:19
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2018-10-30 17:19 UTC
