### ISSUE TITLE
Add new mail/unread badge to dock icon.

### ISSUE THREAD

**Issue by IzsakiRobi** [elementary/mail#1007] opened 2024-12-08 07:19 UTC
### Problem

No red dock icon badges :(

### Proposal

It would be great if the red icon badge returned, like in the old Pantheon mail or Geary mailer.

### Prior Art (Optional)

![Mail_Badge](https://github.com/user-attachments/assets/5dd7e82a-4877-4472-9aef-ae1956c561c1)

**Comment by lenemter** [comment] 2024-12-08 07:26
Duplicate of https://github.com/elementary/mail/issues/290

**Closed by lenemter** 2024-12-08 07:26 UTC

**Comment by IzsakiRobi** [comment] 2024-12-08 07:29
😭🥺
