### ISSUE TITLE
IMAP/SMPTP Checkbox description wrong

### ISSUE THREAD

**Issue by Nine-H** [elementary/mail#371] opened 2019-03-07 01:22 UTC
current:

When adding a new "Other" email server in geary there's a checkbox that says "Use IMAP Credentials" but the dialog uses IMAP credentials by default, and toggling the switch lets you set different SMTP Credentials.

expected:

Change the label to "Don't use IMAP credentials" or "Unique SMTP credentials" so it makes sense.

**Comment by danrabbit** [comment] 2019-03-07 18:08
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2019-03-07 18:08 UTC
