### ISSUE TITLE
mail grows non-stop

### ISSUE THREAD

**Issue by robertsanseries** [elementary/mail#18] opened 2017-05-08 00:42 UTC
Some users reported that as the second column grows, mail grows non-stop. I tested on two pcs and a notebook and the problem really happens.

![captura de tela de 2017-05-07 21-34-16](https://cloud.githubusercontent.com/assets/11967501/25786564/fd8110c8-336d-11e7-8183-98f9817778e2.png)

**Comment by danrabbit** [comment] 2017-05-08 00:48
Closing as a duplicate of #1

**Closed by danrabbit** 2017-05-08 00:48 UTC
