### ISSUE TITLE
allow edit of more fields of account credentials

### ISSUE THREAD

**Issue by josephholsten** [elementary/mail#171] opened 2017-11-09 21:37 UTC
I'm sure most folks don't need to change the mail server or email address of an account. But it seems strange not to allow editing it. I've certainly been in situations where I needed to use my email provider's alternate SMTP port because of ISP blocking.

Fields not editable which should be:
- email address
- imap server
- imap port
- imap encryption
- smtp server
- smtp port
- smtp username
- smtp password
- smpt use imap credentials

**Comment by danrabbit** [comment] 2018-10-17 15:59
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2018-10-17 15:59 UTC
