### ISSUE TITLE
Horizontal elongation

### ISSUE THREAD

**Issue by giovannicaligaris** [elementary/mail#135] opened 2017-08-10 16:16 UTC
Every once in a while Mail goes crazy and it keeps stretching infinitely. 

I know this is a known issue. The only way I can solve this is by reseting the settings from dconf

**dconf reset -f /org/pantheon/mail/**

**Comment by btkostner** [comment] 2017-08-10 16:29
Duplicate of #1

**Closed by btkostner** 2017-08-10 16:29 UTC
