### ISSUE TITLE
Accounts add and edit buttons have really dark highlights on hover

### ISSUE THREAD

**Issue by D0J0P** [elementary/mail#192] opened 2018-02-23 01:07 UTC
If you go into accounts, then hover your mouse over the add and edit buttons, it has a really dark grey color hovering over it, which doesn't happen for those buttons in other apps such as settings where you would see them under Bluetooth or Printer. 

Here's a video showing what I mean: https://www.dropbox.com/s/bnjkd4jldbq801t/Screencast%20from%202018-02-22%2020.01.55.webm?dl=0

**Comment by danrabbit** [comment] 2018-10-17 15:57
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Closed by danrabbit** 2018-10-17 15:57 UTC
