### ISSUE TITLE
Opening emails crashes application

### ISSUE THREAD

**Issue by Yotaanit** [elementary/mail#443] opened 2019-12-27 17:09 UTC
When opening an email, the application just closes.
Some mails don't trigger the crash.

If needed, I can provide a mail which triggers the crash.

elementary OS 5.1 Hera x86_64
Kernel: 4.15.0-72-generic

Error message when rum from terminal:

(pantheon-mail:13991): Gdk-ERROR **: 18:02:23.383: The program 'pantheon-mail' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAlloc (insufficient resources for operation)'.
  (Details: serial 10395 error_code 11 request_code 53 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
fish: “pantheon-mail” terminated by signal SIGTRAP (Trace or breakpoint trap)

**Comment by ryonakano** [comment] 2019-12-28 10:50
Thank you for your report, but this is probably a duplicate of #27.

**Closed by ryonakano** 2019-12-28 10:50 UTC
